### ISSUE TITLE
When the joke page is called several times in a row, the page cannot be scrolled and the voice cannot be broadcast.

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#101]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
When the joke page is called several times in a row, the page cannot be scrolled and the voice cannot be broadcast. then the aplrender template of voice can't  broadcast and then the aplrender template of  page  cannot be scrolled ； I infer that it got stuck after broadcasting problems.

## What is the expected behavior?
Normal page scrolling and voice broadcast

## What behavior are you observing?
When the joke page is called several times in a row, the page cannot be scrolled and voice broadcast

## Provide the steps to reproduce the issue, if applicable:
tell me a joke => home => tell me a joke  => tell me a joke .... it happend

## Tell us about your environment:
 android
### What version of the AVS Device SDK are you using?
    avs sdk 1.24.0

### Tell us what hardware you're using:
other

### Tell us about your OS (Type & version):

Other 
  - android

### Have you tried the same use case with AVS Device SDK SampleApp?

**Comment by sngoc-amazon** [comment]
Hi Gaoseng,

The https://github.com/alexa/alexa-smart-screen-sdk repository does not support Android platforms.
