### ISSUE TITLE
why does not support Android platforms.

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#102]
Hi Gaoseng,

The https://github.com/alexa/alexa-smart-screen-sdk repository does not support Android platforms.

_Originally posted by @sngoc-amazon in https://github.com/alexa/alexa-smart-screen-sdk/issues/101#issuecomment-880386424_

**Comment by sngoc-amazon** [comment]
Hi @gaoseng,

This repository https://github.com/alexa/alexa-smart-screen-sdk does not currently support Android platforms and at this time, we are not aware if Android platform will be supported through this repository in the future.
