### ISSUE TITLE
Did not receive the kindle books interface template when I say that show my kindle books

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#103]
## Briefly summarize your issue:
 when I say that show my kindle books， the devices start speaking book list but it did not show page. I found out that the template was not received during the interaction

## What is the expected behavior?
show page

## What behavior are you observing?
 when I say that show my kindle books， the devices start speaking book list but it did not show page. I found out that the template was not received during the interaction

## Provide the steps to reproduce the issue, if applicable:
show my kindle books

## Tell us about your environment:
 - linux

### What version of the AVS Device SDK are you using?
 - avs device sdk 1.24.0
 - stable version 2.7

### Tell us what hardware you're using:
- Other

### Tell us about your OS (Type & version):
- Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by rpalkar-amzn** [comment]
Hi @gaoseng 

Thank you for reaching out. The Smart Screen SDK relies on directives received from Alexa Voice Service. If a [TemplateRuntime](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/templateruntime.html) or [Alexa.Presentation.APL](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/presentation-apl.html#renderdocument) directive is not received, an utterance may result in voice-only response.
