### ISSUE TITLE
Sometimes the GUI page is abnormal and the renderDocument is received, but the GUI does not support this template. When will you support it?

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#104]
Hi @gaoseng 

Thank you for reaching out. The Smart Screen SDK relies on directives received from Alexa Voice Service. If a [TemplateRuntime](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/templateruntime.html) or [Alexa.Presentation.APL](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/presentation-apl.html#renderdocument) directive is not received, an utterance may result in voice-only response.

_Originally posted by @rpalkar-amzn in https://github.com/alexa/alexa-smart-screen-sdk/issues/103#issuecomment-885330573_

**Comment by rpalkar-amzn** [comment]
Hi @gaoseng 

Thank you for the question. Is this question related to #103 and Kindle experience in particular? Which template is being referred here? It would be helpful if you can provide a documentation/code link about the template.

Please provide the exact the voice utterance for the issue along with the logs for investigating further.

**Comment by gaoseng** [comment]
Thank you for your patience to answer, we have found that it may be caused by the environment, if it recurs in the future, I will provide detailed content
