### ISSUE TITLE
Rapidjson crashes with Release build

### ISSUE THREAD

**Issue by VictorFrench** [alexa/alexa-smart-screen-sdk#105]
We have done AVS/SSSDK build with DCMAKE_BUILD_TYPE=**RELEASE**. When we say "play songs from amazon music", songs starts playing for 2 or 3 seconds but player card not rendered and crashed with rapidjson assertion failed. **This issue is not seen when we try with DCMAKE_BUILD_TYPE=DEBUG**.  I have attached logs for reference.

**From logs(amazon_music_retail_build.txt):**
2021-07-30 07:28:49.202 [ 1d] W AplClientBridge:AplCoreEngine::evaluate.cpp:parseDataBinding : Parse error in '${@viewportProfileGroup == @dividerHeight' - :1:41(41): parse error matching apl::datagrammar::sym_dbend

2021-07-30 07:28:49.261 [ 1d] W AplClientBridge:AplCoreEngine::evaluate.cpp:parseDataBinding : Parse error in '${@fontSizeSmall * @lineHeightMedium$' - :1:36(36): parse error matching apl::datagrammar::sym_dbend

/home/alexa/build/apl-build/rapidjson-prefix/src/rapidjson/include/rapidjson/document.h:1053: rapidjson::GenericValue<Encoding, Allocator>& rapidjson::GenericValue<Encoding, Allocator>::operator[](const rapidjson::GenericValue<Encoding, SourceAllocator>&) [with SourceAllocator = rapidjson::MemoryPoolAllocator<>; Encoding = rapidjson::UTF8<>; Allocator = rapidjson::MemoryPoolAllocator<>]: Assertion `false' failed

## What is the expected behavior?
Player info card to be rendered and song continue to play

## What behavior are you observing?
Song started within 2 or 3 second and crash observed

## Provide the steps to reproduce the issue, if applicable:
Say "Alexa, Play songs from amazon music"

## Tell us about your environment:
AVS SDK - 1.24.0
APL CORE - 1.6.1
SS SDK - 2.7.1

### What version of the AVS Device SDK are you using?
      1.24.0

### Tell us what hardware you're using:
       Other 

### Tell us about your OS (Type & version):
       Linux
**Logs:**
[amazon_music_retail_build.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6916169/amazon_music_retail_build.txt)
[config.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/6916186/config.zip)

**Comment by powj** [comment]
Hi @VictorFrench ,

To help us identify the problem, please can you provide the cmake flags which you used when building:
1. The AVS Device SDK
2. The Smart Screen SDK
3. The APLCore library

**Comment by VictorFrench** [comment]
@powj, This issue is not seen after compiling sample app with apl-core-library/build/rapidjson-prefix/src/rapidjson/include. Hence closing this issue.

Thanks a lot for the support.!!
