### ISSUE TITLE
GUI page does not respond to key events and does not adjust the focus

### ISSUE THREAD

**Issue by Jinglouyan** [alexa/alexa-smart-screen-sdk#108]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

_GUI page does not respond to key events and does not adjust the focus_
## What is the expected behavior?

While runing the sample app with the step on https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/ubuntu.html on a PC . when I say that "show my to-do list"， Alexa will return a list page that shows my to-do list . Then , press the key ArrowDown , focus of the page will move to the first item and highlight it
## What behavior are you observing?

When I built this to my own machine and open the index.html in the same way ,then I say "show my to-do list" and press the key 
ArrowDown ,there's no thing happend . And after a while ,the websocket process crashed
### What version of the AVS Device SDK are you using?
      <2.6>

### Tell us what hardware you're using:
- [ ] Other - tell us more:linux development board with browser

### Tell us about your OS (Type & version):
- [ ] Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.

### Here are some question I want to ask
- [ ] First , I notice that the index.html import the file main.bundle.js，do I need other file to support this ?  Or some files need to be provided to the SDK process ?

**Comment by VaruPan** [comment]
Thanks a lot for reaching out. Upon verification with Alexa Smart Screen SDK 2.6, I am able to see focus on the page moving to the first item with highlight. Can you please share the core dump for the crash?

` First , I notice that the index.html import the file main.bundle.js，do I need other file to support this ? Or some files need to be provided to the SDK process `

main.bundle.js is a js bundle and should have all the dependencies included.

**Comment by Jinglouyan** [comment]
Thanks a lot,we have figured it out .But we find a new problem . We update the SDK version to 2.8, two new problems occured.
(1) press keydown to the fist item ，focus will move to it ,but in sample app ,there are two options at end of tje item ,but in our machine , there is no options .
(2)By using the chrome package on the https://developer.amazon.com/alexa/console/avs/preview/resources/details/SmartScreen%20SDK%20Voice%20Chrome%20Extension ,chrome is shown ,but it do not show the listening state ,just thinking, speaking and others, is it supported the listening state ？Cause the thinking state is showed correctly , I guess that is not a code error , have you ever got this and hava a solution ？ 
Wish to get your reply, thanks
