### ISSUE TITLE
GUI page does not show Alexa state completely

### ISSUE THREAD

**Issue by Jinglouyan** [alexa/alexa-smart-screen-sdk#111]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

GUI page does not show Alexa state completely
## What is the expected behavior?

All Alexa state should be shown on the GUI page as the Linear Chrome animation 
## What behavior are you observing?

Listening state is not be shown
## Provide the steps to reproduce the issue, if applicable:

Use the chrome package on the https://developer.amazon.com/alexa/console/avs/preview/resources/details/SmartScreen%20SDK%20Voice%20Chrome%20Extension to build the main.bundle.js and let the GUI page import it  , then run the AVS Device SDK SampleApp  and say something , chrome is shown as Alexa working state . However , Listening state is not shown ,thinking state is shown , and it disappear with idle state 
### What version of the AVS Device SDK are you using?
Alexa Smart Screen:2.8
Chrome Package:2.4
AVS Device SDK:1.25.0
APL Core Library:1.7.2
### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:Linux TV

### Tell us about your OS (Type & version):
- [ ] Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.

### Addition Information
I am sure about that the listening state message has been transported to GUI page cause I catch it by using chrome browser devtools

**Comment by nguymi91** [comment]
@Jinglouyan ,

Thank you for reporting this issue. Can you please upload the device log for this issue?

Also, without the chrome packing, are you seeing the "LISTENING" state?

Thanks,
Mike

**Comment by Jinglouyan** [comment]
@nguymi91 
[1.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/7250935/1.zip)

Here is the log file
Without the chrome packing, "LISTENING" state can be shown as text at the bottom-right on the page

**Comment by sngoc-amazon** [comment]
Hi @Jinglouyan,

Thank you for the information. I tried reproducing and am able to see listening state.

Can you try a few things to see if you are still seeing the same behavior?
1. Ensure asset files from the voice chrome extension are included in ```~/sdk_folder/ss-build/modules/GUI``` path as indicated in Voice chrome extension README.md
2. Ensure if using Chromium browser, ```--allow-file-access-from-files``` is used as indicated in Voice chrome extension README.md

**Comment by Jinglouyan** [comment]
@sngoc-amazon @sngoc-amazon Sorry for taking so long to reply to you , cause we just had a holiday . 
I am sure of that we use the chrome package correctly because the thinking state can be shown correctly .
In addition , when you launch the Sample APP , use the config file GuiConfigSample_TvOverlayLandscape.json
Can you please have a try with our steps ?
Thanks

**Comment by rpalkar-amzn** [comment]
Hi @Jinglouyan 

Few follow up questions: 

* Are there any errors logged in the browser console when the GUI receives a LISTENING state? 
* Is the sound played from the chrome package on LISTENING?

**Comment by Jinglouyan** [comment]
@rpalkar-amzn Thanks , with your help, we found out that some files were losen , now it can be shown correctly
