### ISSUE TITLE
Alexa smart screen SDK - source skill

### ISSUE THREAD

**Issue by kaygeeyem16** [alexa/alexa-smart-screen-sdk#117]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I have alexa smart screen SDK installed in ubuntu system. I can  run the sample application. In that when I ask for weather or horoscope or any other question I am able to get the result. But in the code how do i know which skill is being called for that utterances.

## What is the expected behavior?
Getting expected result but how do I know where do i see the source skill being called in the code

## What behavior are you observing?
Getting expected result but how do I know where do i see the source skill being called in the code

## Provide the steps to reproduce the issue, if applicable:
In the ubuntu system  run the sample application for alexa smart screen sdk, try asking what is the weather in city. You will see the result in the overlay screen. How do i find from which skill the result is being extracted.

### What version of the AVS Device SDK are you using?
      latest

### Tell us what hardware you're using:
- [ ] Laptop
- [x] Ubuntu
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by VaruPan** [comment]
Thanks for posting this question! Devices advertising support for [Alexa.Presentation.APL](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/presentation-apl.html) will be able to find this information in the payload received with [RenderDocument](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/presentation-apl.html#renderdocument) directive from skills supporting APL.

Here is the property to watch out for: `presentationSession.skillId`

Hope that helps.
