### ISSUE TITLE
Can not pause music in first time show

### ISSUE THREAD

**Issue by longjinxiang** [alexa/alexa-smart-screen-sdk#118]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

On my TV, after I say "play music", I can't use the Remote control to pause the music

## What is the expected behavior?

On the pause button, you can use the remote control to press the OK button to pause the music

## What behavior are you observing?

I can't pause music in first  time.
After I press Right key and Left key, it work.
I guess it was interrupted the first time I pressed the OK button or  get focus error

## Provide the steps to reproduce the issue, if applicable:

Say 'play music' to Alexa, after UI rendering, the music cannot be paused

### What version of the AVS Device SDK are you using?
      <2.8.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by longjinxiang** [comment]
I use remote debug in my TV, this is GUI's log
[alexa_GUI.log](https://github.com/alexa/alexa-smart-screen-sdk/files/7606027/alexa_GUI.log)

**Comment by rpalkar-amzn** [comment]
Hi @longjinxiang 

Thank you for reaching out. Few clarifying questions:

1. Does the pause button on GUI show as focused when music starts playing?
2. Regarding _"I guess it was interrupted the first time I pressed the OK button or get focus error"_, could you elaborate about the error or point out the same in logs?
3. Is this an intermittent issue or does this always occur on first OK remote key press when music starts playing?
4. Is 13 the key code for OK on remote?

**Comment by longjinxiang** [comment]
It was fixed in 2.7.1
