### ISSUE TITLE
WebGL non composite mode support

### ISSUE THREAD

**Issue by aginesh** [alexa/alexa-smart-screen-sdk#119]
## Briefly summarize your issue:
Can the Alexa page be launched on WebGL with non-composite mode enabled?

## What is the expected behavior?
To be able to run Alexa smart screen UI web page on webGL with non-composite mode enabled.

## What behavior are you observing?
Alexa page shows up as a black screen. No UI updates are seen. Only an audio response can be heard.

The smart screen SDK version used is v2.8.0

**Comment by sngoc-amazon** [comment]
Hi @aginesh,

Can you confirm the platform, browser, WebGL, and composite settings you are using?

**Comment by aginesh** [comment]
Hi @sngoc-amazon 
The issue was due to the incorrect settings of the browser. Please ignore this item.
