### ISSUE TITLE
No smart screen content displayed while AVS is speaking.

### ISSUE THREAD

**Issue by zhaokai3000** [alexa/alexa-smart-screen-sdk#128]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After saying "alexa, tell me a story", alexa state changed from thinking to idle immediately. Nothing but the initial "say alexa to talk"   string is displayed on smart screen while AVS is telling me a story.

## What is the expected behavior?

Smart screen displays the story information while AVS is speaking.

## What behavior are you observing?

Nothing but the initial "say alexa to talk"   string is displayed on smart screen while AVS is telling me a story.

## Provide the steps to reproduce the issue, if applicable:

1st we customized the avs  device sdk to use a audio input process engine, avs sample app works fine, the state seems right while we make a call like "alexa, tell me a joke", the state change from idle to listening to thinking to speaking, and to idle again after speaking.
2nd port the changes to avs sample app to alexa smart screen sample app.
3rd run the alexa smart screen sample app.

## Tell us about your environment:

  avs device sdk version 1.26.0;
  alexa smart screen sdk version 2.9.0;
  websocketpp version 0.8.2;
  apl-core-library version 1.8.1;
  apl-client-library version 1.8.2.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more:
          arm development board, 2mics and 1playback.

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [x] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

logs maybe relevant (more logs refer to the log file attached):
#####################################
#       ALEXA STATE: THINKING       #
#####################################

2022-04-08 09:08:14.168 [ 14] 0 GUIManager:ChannelFocusChanged:channelName=Content,newFocus=BACKGROUND
2022-04-08 09:08:14.169 [  5] E AplClientBridge:invokeExtensionEventHandlerFailed::Root context is missing
#################################
#       ALEXA STATE: IDLE       #
#################################

2022-04-08 09:08:14.312 [ 14] 0 GUIManager:ChannelFocusChanged:channelName=Dialog,newFocus=NONE
2022-04-08 09:08:14.312 [ 14] 0 GUIManager:ChannelFocusChanged:channelName=Content,newFocus=FOREGROUND
2022-04-08 09:08:16.693 [  5] E AplClientBridge:invokeExtensionEventHandlerFailed::Root context is missing
2022-04-08 09:08:16.697 [  5] E GUIManager:getAudioItemOffset:reason=Null MediaPropertiesInterface
2022-04-08 09:08:16.713 [  5] E GUIManager:getAudioItemOffset:reason=Null MediaPropertiesInterface
2022-04-08 09:08:16.729 [  5] E GUIManager:getAudioItemOffset:reason=Null MediaPropertiesInterface
2022-04-08 09:08:16.746 [  5] E GUIManager:getAudioItemOffset:reason=Null MediaPropertiesInterface
2022-04-08 09:08:16.762 [  5] E GUIManager:getAudioItemOffset:reason=Null MediaPropertiesInterface
2022-04-08 09:08:16.778 [  5] E GUIManager:getAudioItemOffset:reason=Null MediaPropertiesInterface
2022-04-08 09:08:16.794 [  5] E GUIManager:getAudioItemOffset:reason=Null MediaPropertiesInterface

[alexa smart screen error log.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/8451165/alexa.smart.screen.error.log.txt)

**Comment by powj** [comment]
Hi @zhaokai3000 , I am unable to reproduce this on our reference SampleApp, can you confirm if you see any visuals for other utterances, such as weather?

From your logs I see a few errors when APL package dependencies are downloaded: 
`2022-04-08 09:09:21.466 [ 1b] E CachingDownloadManager:downloadFromSourceFailed:statusCode=HTTP_RESPONSE_CODE_UNDEFINED,reason=nonSuccessStatusCodeFromGetHeader`

The failure to download APL dependencies will cause an issue so you may wish to investigate why your device is receiving undefined response codes when attempting to perform the download. This function is likely where you would want to start the investigation: https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/Alexa/SampleApp/src/CachingDownloadManager.cpp#L198

**Comment by zhaokai3000** [comment]
Thanks for your quick response @powj 
Nothing is displayed for utterances like weather, but the log of status seems ok:

**Comment by powj** [comment]
Can you share your smart screen sdk configuration json file? 

It appears that you are using a non-standard screen resolution which is causing APL document inflation to fail. There are a number of pre-defined viewport profiles listed [here](https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-select-the-viewport-profiles-your-skill-supports.html#how-different-devices-display-your-apl-content) , the APL runtime will attempt to scale documents, however if your configuration does not fall into one of these categories then APL documents may either fail to render correctly, or will not render at all.

**Comment by zhaokai3000** [comment]
I tried to display the smart screen in a 750*430 pixel window on a lcd screen, the resolution I used may'be is not standard as you mentioned. Which profile do you suggest that I should follow?
Here is my smart screen sdk configuration json file:
{
  "sampleApp": {
    "websocketInterface":"127.0.0.1",
    "websocketPort":8933,
    "websocketCertificateAuthority":"/etc/avs/certs/ca.cert",
    "websocketCertificate":"/etc/avs/certs/server.chain",
    "websocketPrivateKey":"/etc/avs/certs/server.key"
  },
  "alexaPresentationCapabilityAgent": {
    // The minimum state reporting interval in milliseconds for the AlexaPresentation CA
    // "minStateReportIntervalMs": 600
    // The interval between checks for context changes
    // "stateReportCheckIntervalMs": 2000
  },
  "gui": {
    "appConfig": {
      "description": "Smart Screen Sample UI",
      "mode": "TV",
      "emulateDisplayDimensions": true,
      "scaleToFill": true,
      "audioInputInitiator": "WAKEWORD",
      "windows": [
        {
          "id": "tvFullscreen",
          "templateId": "tvFullscreen",
          "sizeConfigurationId": "fullscreen",
          "interactionMode": "tv",
          "supportedExtensions": [
            "aplext:backstack:10"
          ]
        },
        {
          "id": "tvOverlayLandscape",
          "templateId": "tvOverlayLandscape",
          "windowPosition": "bottom",
          "sizeConfigurationId": "landscapePanel",
          "interactionMode": "tv_overlay",
          "supportedExtensions": [
            "aplext:backstack:10"
          ]
        }
      ],
      "defaultWindowId": "tvFullscreen",
      "deviceKeys": {
        "talkKey": {
          "code": "KeyA",
          "keyCode": 65,
          "key": "a"
        },
        "backKey": {
          "code": "KeyB",
          "keyCode": 66,
          "key": "b"
        },
        "exitKey": {
          "code": "Escape",
          "keyCode": 27,
          "key": "Escape"
        },
        "toggleCaptionsKey": {
          "code": "KeyC",
          "keyCode": 67,
          "key": "c"
        },
        "toggleDoNotDisturbKey": {
          "code": "KeyD",
          "keyCode": 68,
          "key": "d"
        }
      }
    },
    "visualCharacteristics": [
      {
        "type": "AlexaInterface",
        "interface": "Alexa.InteractionMode",
        "version": "1.1",
        "configurations": {
          "interactionModes": [
            {
              "id": "tv",
              "uiMode": "TV",
              "interactionDistance": {
                "unit": "INCHES",
                "value": 130
              },
              "touch": "UNSUPPORTED",
              "keyboard": "SUPPORTED",
              "video": "SUPPORTED",
              "dialog": "SUPPORTED"
            },
            {
              "id": "tv_overlay",
              "uiMode": "TV",
              "interactionDistance": {
                "unit": "INCHES",
                "value": 130
              },
              "touch": "UNSUPPORTED",
              "keyboard": "SUPPORTED",
              "video": "UNSUPPORTED",
              "dialog": "SUPPORTED"
            }
          ]
        }
      },
      {
        "type": "AlexaInterface",
        "interface": "Alexa.Presentation.APL.Video",
        "version": "1.0",
        "configurations": {
          "video": {
            "codecs": [
              "H_264_42",
              "H_264_41"
            ]
          }
        }
      },
      {
        "type": "AlexaInterface",
        "interface": "Alexa.Display.Window",
        "version": "1.0",
        "configurations": {
          "templates": [
            {
              "id": "tvFullscreen",
              "type": "STANDARD",
              "configuration": {
                "sizes": [
                  {
                    "type": "DISCRETE",
                    "id": "fullscreen",
                    "value": {
                      "unit": "PIXEL",
                      "value": {
                        "width": 1520,
                        "height": 860
                      }
                    }
                  }
                ],
                "interactionModes": [
                  "tv"
                ]
              }
            },
            {
              "id": "tvOverlayLandscape",
              "type": "OVERLAY",
              "configuration": {
                "sizes": [
                  {
                    "type": "DISCRETE",
                    "id": "landscapePanel",
                    "value": {
                      "unit": "PIXEL",
                      "value": {
                        "width": 1520,
                        "height": 860
                      }
                    }
                  }
                ],
                "interactionModes": [
                  "tv_overlay"
                ]
              }
            }
          ]
        }
      },
      {
        "type": "AlexaInterface",
        "interface": "Alexa.Display",
        "version": "1.0",
        "configurations": {
          "display": {
            "type": "PIXEL",
            "touch": [
              "UNSUPPORTED"
            ],
            "shape": "RECTANGLE",
            "dimensions": {
              "resolution": {
                "unit": "PIXEL",
                "value": {
                  "width": 1520,
                  "height": 860
                }
              },
              "physicalSize": {
                "unit": "INCHES",
                "value": {
                  "width": 56.7,
                  "height": 31.9
                }
              },
              "pixelDensity": {
                "unit": "DPI",
                "value": 160
              },
              "densityIndependentResolution": {
                "unit": "DP",
                "value": {
                  "width": 1520,
                  "height": 860
                }
              }
            }
          }
        }
      }
    ],
    "liveViewControllerOptions": {
      "physicalMicButtonHint": {
        "micButtonHintType": "Text",
        "micButtonHintSource": "A"
      },
      "viewingDeviceMicUnsupported": false
    }
  }
}

**Comment by powj** [comment]
The TV viewport is designed for 16:9 aspect ratios (such as 1920x1080). For your display, to get visuals which render reliably you may need to use/modify a hub profile (https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/config/guiConfigSamples/GuiConfigSample_SmartScreenLargeLandscape.json).

Please note however that if you require content to be navigable with a remote then this is only supported with a uiMode of "TV"

**Comment by zhaokai3000** [comment]
@powj Thanks! I'll have a try.
