### ISSUE TITLE
D-pad support

### ISSUE THREAD

**Issue by aginesh** [alexa/alexa-smart-screen-sdk#13]
## Briefly summarize your issue:
Is D-pad supported? Is it possible to navigate on the page(ex: while playing music) and select next song or play/pause using arrow keys and enter key?

## What is the expected behavior?
To navigate different buttons on the page and be able to select.

## What behavior are you observing?
No action when using navigation keys.
The navigation events defined in the following header file only has back and exit keys. Arrow keys and enter keys are not seen.
Alexa/SmartScreenSDKInterfaces/include/SmartScreenSDKInterfaces/NavigationEvent.h

## Provide the steps to reproduce the issue, if applicable:
1. Alexa play "taylor swift" from iHeart radio or bring up any page that has items to select and/or navigate.
2. Try navigating the page using arrow keys and select play/pause, next song, like/dislike song

## Tell us about your environment:
alexa-smart-screen-sdk v 2.0.1

### Tell us what hardware you're using:
Raspberry Pi

### Tell us about your OS (Type & version):
 Linux

**Comment by priyagsenthil** [comment]
Hi,

We do support D-pad navigation and on retest seems to be working fine. Could you send a video attachment showing the issue.

Thanks
Priya

**Comment by aginesh** [comment]
Here is a link to the video showing the problem.
https://photos.app.goo.gl/sg7ZSbx64pd9Y17QA

The arrow keys did not respond.
The back key 'b' did respond.

**Comment by jchenit122** [comment]
Hi @aginesh 

We have a ticket created to track this issue. 

It also seems D-pad navigation will work if you don't click on the screen, please check. 

Thanks
Jason
