### ISSUE TITLE
Open Jeopardy after start music or news, music or news not stopped.

### ISSUE THREAD

**Issue by zhaokai3000** [alexa/alexa-smart-screen-sdk#134]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

After starting music or news, try to ask Alexa to open Jeopardy. News or music still playing in the background, while Jeopardy is playing in the front. Two sounds mixed together.

## What is the expected behavior?

News broadcast is stopped after Jeopardy starts.

## What behavior are you observing?

Still broadcasting news while Jeopardy is playing.

## Provide the steps to reproduce the issue, if applicable:

Step1. Ask Alexa for some news, start broadcasting flash briefings;
Step2, Ask Alexa to open Jeopardy.

### What version of the AVS Device SDK are you using?
2.9.2

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [x] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by powj** [comment]
Thank you for bringing this to our attention, we have been able to reproduce this issue and will be investigating.

**Comment by 1cengizk** [comment]
@zhaokai3000 You can apply the following patch as a workaround for this problem, while we are working on a permanent fix.

You can modify the following three lines as follows and then rebuild: https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/lib/media/AVSAudioPlayer.ts#L93-L95

```
super.onError(id, reason);
if (reason.toString().includes(`TypeError: Cannot read properties of undefined (reading 'component')`)) return;
this.playing = false;
```

**Comment by zhaokai3000** [comment]
> @zhaokai3000 You can apply the following patch as a workaround for this problem, while we are working on a permanent fix.
> 
> You can modify the following lines as follows and then rebuild: https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/lib/media/AVSAudioPlayer.ts#L93-L94
> 
> ```
> super.onError(id, reason);
> if (reason.toString().includes(`TypeError: Cannot read properties of undefined (reading 'component')`)) return;
> this.playing = false;
> ```

Will try. Thanks!

**Comment by zhaokai3000** [comment]
`    public onError(id : string, reason : string) : void {
        super.onError(id, reason);
        if (reason.toString().includes(`TypeError: Cannot read properties of undefined (reading 'component')`)) {
            return;
        }
        this.playing = false;
        this.releaseFocus();
        if (this.activityToken !== undefined) {
            this.activityTracker.recordInactive(this.activityToken);
            this.activityToken = undefined;
        }
    }
`
@1cengizk Sorry but the workround seems doesn't work. Still have news mixed with Jeopardy sounds.

**Comment by powj** [comment]
Hi @zhaokai3000, could you add `console.log(reason);` at the beginning of the `onError` function above, then provide the console logs from your browser.

**Comment by zhaokai3000** [comment]
console log for the reason:
`TypeError: Cannot read property 'component' of undefined`

**Comment by powj** [comment]
Thank you for providing these logs, to enable both cases to be caught I recommend modifying the check to be:
`if (reason.toString().includes("TypeError:")) return;`

**Comment by zhaokai3000** [comment]
The workaround patch works. Thanks!
