### ISSUE TITLE
[Q&A] Do Alexa Smart Screen support Android?

### ISSUE THREAD

**Issue by AlexTraan** [alexa/alexa-smart-screen-sdk#137]
Hi Team,

Do Alexa Smart Screen support Android?
As i guess, Alexa Smart Screen based on HTML rendering, so it will OK for Android, iOS, Windows,... because all of them support Web browser

**Comment by 1cengizk** [comment]
Hi @AlexTraan,

Android is not officially supported by Alexa Smart Screen SDK. It is officially supported on the following platforms:

https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/overview.html
