### ISSUE TITLE
Platform conformity: emulating Broadcom BCM972180 Voice STB Development Kit

### ISSUE THREAD

**Issue by FCLC** [alexa/alexa-smart-screen-sdk#147]
Trying to get started on my end, but won't be able to always access the dev kit. Just so I know (roughly) what I'm getting into I'm going to spin up a QEMU box and would like to match the specifications of the dev kit as closely as possible. (I'll be emulating via a more powerful ARM system) 
Im having trouble tracking down the specifics of instruction set capabilities of the onboard Broadcom BCM72180. 

I know it's a 64 bit quad core, but that's where my search engines seem to run dry. Any insight? Want to make sure I'm targeting the right instruction sets across builds.

**Comment by VaruPan** [comment]
Hi @FCLC, thanks a lot for reaching out to Alexa Team!

There are couple of things - 
1. If you are just getting started, I would highly recommend to start with the latest [AVS Device SDK](https://github.com/alexa/avs-device-sdk) 3.0 that enables _both_ headless and smart-screen platforms to develop Alexa built-in devices. Here is the [documentation](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/overview.html) to get you started.
2. Alexa Device SDK (and Alexa Smart Screen SDK) are verified on many [reference platforms](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/ipcserver-sample-app.html#quick-start-guides). Anyone is welcome to port the SDK (and reference sample application) on platforms of their choice.
3. From you description, a good starting point could be the Raspberry Pi [Quick Start Guide](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/smart-screen-raspberry-pi.html) which targets ARM based platforms in general.
4. And finally, in case you decide to use the older version of SDK stack, you will find the guide [here](https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html).

Will you all this best!
Varun

**Comment by FCLC** [comment]
Hi @VaruPan! Thanks for the advice. We're probably going to be ordering in some of the Broadcom dev kits since they significantly more powerful than the Pi and also support AV1 amongst other features(as a total platform) Since the lead time on those devices can be quite long, I'm looking to nail down what the specification for the dev kit is. 

Documentation is quite sparse as of now. 

The idea is to get as close as possible using an NV jetson platform while we wait for the validated but more powerful development hardware to arrive.
