### ISSUE TITLE
Android Quick Start Guide

### ISSUE THREAD

**Issue by maciejmiarecki** [alexa/alexa-smart-screen-sdk#15]
## Briefly summarize your issue:
Are you planning to add a quick start guide for Android OS?

## What is the expected behavior?
n/a

## What behavior are you observing?
n/a

## Provide the steps to reproduce the issue, if applicable:
n/a

### What version of the AVS Device SDK are you using?
n/a

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [x] Other - tell us more: Android powered device

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more: Android

**Comment by priyagsenthil** [comment]
Hi maciejmiarecki,

Android is not one of the currently supported platforms for the SmartScreen SDK.

Thanks
Priya
