### ISSUE TITLE
Wrong path to SmartScreenSDKConfig.json in macOS Quick Start Guide

### ISSUE THREAD

**Issue by maciejmiarecki** [alexa/alexa-smart-screen-sdk#16]
## Briefly summarize your issue:
Command to run the sample app (Step 8) contains incorrect path to SmartScreenSDKConfig.json.
https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/mac-os.html#step-8-run-the-alexa-smart-screen-sdk-sample-app

## What is the expected behavior?
The path could be for example:
`~/sdk_folder/alexa-smart-screen-sdk/modules/GUI/config/SmartScreenSDKConfig.json`

## What behavior are you observing?
SmartScreenSDKConfig.json doesn't exists in specified path.

## Provide the steps to reproduce the issue, if applicable:
n/a

### What version of the AVS Device SDK are you using?
2.0.1

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [x] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by priyagsenthil** [comment]
Hi maciejmiarecki,

Thanks for bringing this to our attention. We will be fixing the documentation with the next release of the SDK.

Thanks
Priya
