### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by aginesh** [alexa/alexa-smart-screen-sdk#20]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Memory usage by SampleApp from Smart screen SDK keeps increasing.

## What is the expected behavior?
Memory usage remains about the same as when the process is started.

## What behavior are you observing?
Memory usage as seen from "top" command %mem or System monitor tool keeps increasing.

## Provide the steps to reproduce the issue, if applicable:
1. start smart screen SDK app
2. check %mem from "top" command for SampleApp or memory value from System monitor tool.
3. Issue a command. Ex: "Alexa, what is the capital of Brazil"
4. System gives audio response and also a pop up is shown on screen with flag of the country.
5. Wait for the pop up to get dismissed.
6. Issue another command. Ex: "Alexa, what is the capital of Japan"
7. System responds and pop up with country flag is shown on screen
8. wait for the pop up to get dismissed.
9. repeat from step 3 onwards.

After several repetitions, 100+ check top command or system monitor. The memory values for SampleApp would have gone up.

On systems with lower memory, sample app crashes after about 20 hrs due to a lack of available memory.

## Tell us about your environment:
using device sdk version 1.15 and smart screen sdk v2.0.1 running on Ubuntu 16.04 LTS.

### Tell us what hardware you're using:
- [+] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [+] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by chemudug-amzn** [comment]
Hi aginesh,

Thank you for reporting this to us, we are taking a look and post an update after diagnosing on our side.

**Comment by nguymi91** [comment]
We're tracking this issue internally and we'll address this issue in future releases.

**Comment by zhtqfkj** [comment]
> We're tracking this issue internally and we'll address this issue in future releases.

we used device sdk version 1.19.0 and smart screen sdk v2.0.2 running on Ubuntu 16.04 LTS.
And used Valgrind-3.13.0 to track the memory leak, please refe to the report.
[20200511183905log.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/4613305/20200511183905log.txt)
