### ISSUE TITLE
Build Alexa Smart Screen SDK Error

### ISSUE THREAD

**Issue by shenhuaz** [alexa/alexa-smart-screen-sdk#23]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

it will do a unit test by Ctest when build smart screen sdk, and all my test cases are failed, it will show error after that.
## What is the expected behavior?

it should show as official website like these:
[  5%] Built target AlexaPresentation
[ 15%] Built target gmock_main
[ 21%] Built target AlexaPresentationTest
[ 26%] Built target SmartScreenTemplateRunTime
[ 31%] Built target TemplateRuntimeTest
[ 42%] Built target SmartScreenClient
[100%] Built target SampleApp
## What behavior are you observing?

[  8%] Built target VisualCharacteristics
[ 26%] Built target gmock_main
[ 34%] Built target VisualCharacteristicsTest
[ 43%] Built target AlexaPresentation
[ 52%] Built target AlexaPresentationTest
[ 60%] Built target SmartScreenTemplateRunTime
[ 69%] Built target TemplateRuntimeTest
Test project /home/payne/Payne/BSH/AVS_SDK/ss-build/modules/Alexa
      Start  1: AlexaPresentationTest.testNullContextManagerInterface
 1/37 Test  #1: AlexaPresentationTest.testNullContextManagerInterface ......................***Failed    0.00 sec
      Start  2: AlexaPresentationTest.testNullFocusManagerInterface
 2/37 Test  #2: AlexaPresentationTest.testNullFocusManagerInterface ........................***Failed    0.00 sec
      Start  3: AlexaPresentationTest.testNullExceptionSender
 3/37 Test  #3: AlexaPresentationTest.testNullExceptionSender ..............................***Failed    0.00 sec
      Start  4: AlexaPresentationTest.testNullMessageSender
 4/37 Test  #4: AlexaPresentationTest.testNullMessageSender ................................***Failed    0.00 sec
      Start  5: AlexaPresentationTest.testUnknownDirective
 5/37 Test  #5: AlexaPresentationTest.testUnknownDirective .................................***Failed    0.00 sec
      Start  6: AlexaPresentationTest.testMalformedRenderDocumentDirective
 6/37 Test  #6: AlexaPresentationTest.testMalformedRenderDocumentDirective .................***Failed    0.00 sec
      Start  7: AlexaPresentationTest.testMalformedRenderDocumentDirective2
 7/37 Test  #7: AlexaPresentationTest.testMalformedRenderDocumentDirective2 ................***Failed    0.00 sec
      Start  8: AlexaPresentationTest.testMalformedExecuteCommandDirective
 8/37 Test  #8: AlexaPresentationTest.testMalformedExecuteCommandDirective .................***Failed    0.00 sec
      Start  9: AlexaPresentationTest.testMalformedExecuteCommandDirective2
 9/37 Test  #9: AlexaPresentationTest.testMalformedExecuteCommandDirective2 ................***Failed    0.00 sec
      Start 10: AlexaPresentationTest.testExecuteCommandAfterMismatchedAPLCard
10/37 Test #10: AlexaPresentationTest.testExecuteCommandAfterMismatchedAPLCard .............***Failed    0.00 sec
      Start 11: AlexaPresentationTest.testExecuteCommandAfterRightAPL
11/37 Test #11: AlexaPresentationTest.testExecuteCommandAfterRightAPL ......................***Not Run (Disabled)   0.00 sec
      Start 12: AlexaPresentationTest.testAPLClearCard
12/37 Test #12: AlexaPresentationTest.testAPLClearCard .....................................***Failed    0.00 sec
      Start 13: AlexaPresentationTest.testAPLTimeout
13/37 Test #13: AlexaPresentationTest.testAPLTimeout .......................................***Failed    0.00 sec
      Start 14: AlexaPresentationTest.testAPLIdleRespectsGUIActive
14/37 Test #14: AlexaPresentationTest.testAPLIdleRespectsGUIActive .........................***Failed    0.00 sec
      Start 15: AlexaPresentationTest.testAPLIdleRespectsGUIInactive
15/37 Test #15: AlexaPresentationTest.testAPLIdleRespectsGUIInactive .......................***Failed    0.00 sec
      Start 16: AlexaPresentationTest.testAPLIdleRespectsDialogUXWhenGUIInactive
16/37 Test #16: AlexaPresentationTest.testAPLIdleRespectsDialogUXWhenGUIInactive ...........***Failed    0.00 sec
      Start 17: AlexaPresentationTest.testAPLFollowedByAPL
17/37 Test #17: AlexaPresentationTest.testAPLFollowedByAPL .................................***Failed    0.00 sec
      Start 18: AlexaPresentationTest.testSendUserEvent
18/37 Test #18: AlexaPresentationTest.testSendUserEvent ....................................***Failed    0.00 sec
      Start 19: TemplateRuntimeTest.test_nullAudioPlayerInterface
19/37 Test #19: TemplateRuntimeTest.test_nullAudioPlayerInterface ..........................***Failed    0.00 sec
      Start 20: TemplateRuntimeTest.test_nullFocusManagerInterface
20/37 Test #20: TemplateRuntimeTest.test_nullFocusManagerInterface .........................***Failed    0.00 sec
      Start 21: TemplateRuntimeTest.test_nullExceptionSender
21/37 Test #21: TemplateRuntimeTest.test_nullExceptionSender ...............................***Failed    0.00 sec
      Start 22: TemplateRuntimeTest.test_renderInfoCardsPlayersAddRemoveObserver
22/37 Test #22: TemplateRuntimeTest.test_renderInfoCardsPlayersAddRemoveObserver ...........***Failed    0.00 sec
      Start 23: TemplateRuntimeTest.test_unknownDirective
23/37 Test #23: TemplateRuntimeTest.test_unknownDirective ..................................***Failed    0.00 sec
      Start 24: TemplateRuntimeTest.testSlow_renderTemplateDirective
24/37 Test #24: TemplateRuntimeTest.testSlow_renderTemplateDirective .......................***Failed    0.00 sec
      Start 25: TemplateRuntimeTest.test_handleDirectiveImmediately
25/37 Test #25: TemplateRuntimeTest.test_handleDirectiveImmediately ........................***Failed    0.00 sec
      Start 26: TemplateRuntimeTest.testSlow_renderPlayerInfoDirectiveBefore
26/37 Test #26: TemplateRuntimeTest.testSlow_renderPlayerInfoDirectiveBefore ...............***Failed    0.00 sec
      Start 27: TemplateRuntimeTest.test_renderPlayerInfoDirectiveAfter
27/37 Test #27: TemplateRuntimeTest.test_renderPlayerInfoDirectiveAfter ....................***Failed    0.00 sec
      Start 28: TemplateRuntimeTest.test_renderPlayerInfoDirectiveWithoutAudioItemId
28/37 Test #28: TemplateRuntimeTest.test_renderPlayerInfoDirectiveWithoutAudioItemId .......***Failed    0.00 sec
      Start 29: TemplateRuntimeTest.test_malformedRenderPlayerInfoDirective
29/37 Test #29: TemplateRuntimeTest.test_malformedRenderPlayerInfoDirective ................***Failed    0.00 sec
      Start 30: TemplateRuntimeTest.test_renderPlayerInfoDirectiveDifferentAudioItemId
30/37 Test #30: TemplateRuntimeTest.test_renderPlayerInfoDirectiveDifferentAudioItemId .....***Failed    0.00 sec
      Start 31: TemplateRuntimeTest.test_renderPlayerInfoDirectiveWithTwoProviders
31/37 Test #31: TemplateRuntimeTest.test_renderPlayerInfoDirectiveWithTwoProviders .........***Failed    0.00 sec
      Start 32: TemplateRuntimeTest.test_renderPlayerInfoDirectiveAudioStateUpdate
32/37 Test #32: TemplateRuntimeTest.test_renderPlayerInfoDirectiveAudioStateUpdate .........***Failed    0.00 sec
      Start 33: TemplateRuntimeTest.test_focusNone
33/37 Test #33: TemplateRuntimeTest.test_focusNone .........................................***Failed    0.00 sec
      Start 34: TemplateRuntimeTest.test_displayCardCleared
34/37 Test #34: TemplateRuntimeTest.test_displayCardCleared ................................***Failed    0.00 sec
      Start 35: TemplateRuntimeTest.test_reacquireChannel
35/37 Test #35: TemplateRuntimeTest.test_reacquireChannel ..................................***Failed    0.00 sec
      Start 36: TemplateRuntimeTest.testTimer_RenderPlayerInfoAfterPlayerActivityChanged
36/37 Test #36: TemplateRuntimeTest.testTimer_RenderPlayerInfoAfterPlayerActivityChanged ...***Failed    0.00 sec
      Start 37: VisualCharacteristicsTest.testGetCapabilityConfigurations
37/37 Test #37: VisualCharacteristicsTest.testGetCapabilityConfigurations ..................***Not Run (Disabled)   0.00 sec

0% tests passed, 35 tests failed out of 35

Total Test time (real) =   0.10 sec

The following tests did not run:
	 11 - AlexaPresentationTest.testExecuteCommandAfterRightAPL (Disabled)
	 37 - VisualCharacteristicsTest.testGetCapabilityConfigurations (Disabled)

The following tests FAILED:
	  1 - AlexaPresentationTest.testNullContextManagerInterface (Failed)
	  2 - AlexaPresentationTest.testNullFocusManagerInterface (Failed)
	  3 - AlexaPresentationTest.testNullExceptionSender (Failed)
	  4 - AlexaPresentationTest.testNullMessageSender (Failed)
	  5 - AlexaPresentationTest.testUnknownDirective (Failed)
	  6 - AlexaPresentationTest.testMalformedRenderDocumentDirective (Failed)
	  7 - AlexaPresentationTest.testMalformedRenderDocumentDirective2 (Failed)
	  8 - AlexaPresentationTest.testMalformedExecuteCommandDirective (Failed)
	  9 - AlexaPresentationTest.testMalformedExecuteCommandDirective2 (Failed)
	 10 - AlexaPresentationTest.testExecuteCommandAfterMismatchedAPLCard (Failed)
	 12 - AlexaPresentationTest.testAPLClearCard (Failed)
	 13 - AlexaPresentationTest.testAPLTimeout (Failed)
	 14 - AlexaPresentationTest.testAPLIdleRespectsGUIActive (Failed)
	 15 - AlexaPresentationTest.testAPLIdleRespectsGUIInactive (Failed)
	 16 - AlexaPresentationTest.testAPLIdleRespectsDialogUXWhenGUIInactive (Failed)
	 17 - AlexaPresentationTest.testAPLFollowedByAPL (Failed)
	 18 - AlexaPresentationTest.testSendUserEvent (Failed)
	 19 - TemplateRuntimeTest.test_nullAudioPlayerInterface (Failed)
	 20 - TemplateRuntimeTest.test_nullFocusManagerInterface (Failed)
	 21 - TemplateRuntimeTest.test_nullExceptionSender (Failed)
	 22 - TemplateRuntimeTest.test_renderInfoCardsPlayersAddRemoveObserver (Failed)
	 23 - TemplateRuntimeTest.test_unknownDirective (Failed)
	 24 - TemplateRuntimeTest.testSlow_renderTemplateDirective (Failed)
	 25 - TemplateRuntimeTest.test_handleDirectiveImmediately (Failed)
	 26 - TemplateRuntimeTest.testSlow_renderPlayerInfoDirectiveBefore (Failed)
	 27 - TemplateRuntimeTest.test_renderPlayerInfoDirectiveAfter (Failed)
	 28 - TemplateRuntimeTest.test_renderPlayerInfoDirectiveWithoutAudioItemId (Failed)
	 29 - TemplateRuntimeTest.test_malformedRenderPlayerInfoDirective (Failed)
	 30 - TemplateRuntimeTest.test_renderPlayerInfoDirectiveDifferentAudioItemId (Failed)
	 31 - TemplateRuntimeTest.test_renderPlayerInfoDirectiveWithTwoProviders (Failed)
	 32 - TemplateRuntimeTest.test_renderPlayerInfoDirectiveAudioStateUpdate (Failed)
	 33 - TemplateRuntimeTest.test_focusNone (Failed)
	 34 - TemplateRuntimeTest.test_displayCardCleared (Failed)
	 35 - TemplateRuntimeTest.test_reacquireChannel (Failed)
	 36 - TemplateRuntimeTest.testTimer_RenderPlayerInfoAfterPlayerActivityChanged (Failed)
Errors while running CTest
modules/Alexa/CMakeFiles/unit.dir/build.make:57: recipe for target 'modules/Alexa/CMakeFiles/unit' failed
make[2]: *** [modules/Alexa/CMakeFiles/unit] Error 8
CMakeFiles/Makefile2:516: recipe for target 'modules/Alexa/CMakeFiles/unit.dir/all' failed
make[1]: *** [modules/Alexa/CMakeFiles/unit.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

## Provide the steps to reproduce the issue, if applicable:

I build AVS Device SDK and APL Core Library, they are fine.
my cmake command for Alexa smart screen sdk:
CC=$CC CXX=$CXX PKG_CONFIG_PATH=$PKG_CONFIG_PATH cmake -DCMAKE_PREFIX_PATH=/home/payne/new/BSH/AVS_SDK/AVS_install -DWEBSOCKETPP_INCLUDE_DIR=/home/payne/new/BSH/AVS_SDK/third-party/websocketpp-0.8.1 -DDISABLE_WEBSOCKET_SSL=ON -DGSTREAMER_MEDIA_PLAYER=ON -DCMAKE_BUILD_TYPE=DEBUG -DAPL_CORE=ON -DAPLCORE_INCLUDE_DIR=/home/payne/new/BSH/AVS_SDK/apl-core-library/aplcore/include -DAPLCORE_LIB_DIR=/home/payne/new/BSH/AVS_SDK/apl-core-library/build/aplcore -DYOGA_INCLUDE_DIR=/home/payne/new/BSH/AVS_SDK/apl-core-library/build/yoga-prefix/src/yoga -DYOGA_LIB_DIR=/home/payne/new/BSH/AVS_SDK/apl-core-library/build/lib ../alexa-smart-screen-sdk

-- Toolchain file defaulted to '/usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/share/cmake/OEToolchainConfig.cmake'
-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++
-- Check for working CXX compiler: /usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/pkg-config (found version "0.29.2")
-- Checking for module 'AlexaClientSDK=1.15.0'
-- Found AlexaClientSDK, version 1.15.0
Creating the build directory for the AlexaModule with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
-- Checking for modules 'gstreamer-1.0>=1.8;gstreamer-app-1.0>=1.8'
-- Found gstreamer-1.0, version 1.14.4
-- Found gstreamer-app-1.0, version 1.14.4
Bluetooth implementation not supported
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: /usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc
-- Check for working C compiler: /usr/local/oecore-x86_64/sysroots/x86_64-oesdk-linux/usr/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.17")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
Creating the build directory for the CapabilityAgents with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
Creating the build directory for the ApplicationUtilities with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the Communication with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the SmartScreenClient with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
To build the sample app, please enable microphone and media player modules.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
FATALDoxygen is required to generate documentation.
Creating the build directory for the Utils with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Configuring done
-- Generating done
CMake Warning:
Manually-specified variables were not used by the project:

APLCORE_INCLUDE_DIR
APLCORE_LIB_DIR
APL_CORE
YOGA_INCLUDE_DIR
YOGA_LIB_DIR
-- Build files have been written to: /home/payne/new/BSH/AVS_SDK/ss-build

### What version of the AVS Device SDK are you using?
      <1.15.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [v ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ v] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by nguymi91** [comment]
Hi @shenhuaz 

Have you gotten the Alexa Device SDK running successfully on your dev machine? You can also try to run their unit test via "make test" in the build folder for Alexa Device SDK.

I'm thinking there might be some dependencies issue with your build. Please running unit tests and the sample app in Alexa Device SDK and let me know!

Thanks,
Mike

**Comment by shenhuaz** [comment]
hi @nguymi91 
 
    unit tests in Alexa Device SDK are failed. I think this issue may relate to my build environment. 
I build it on my Ubuntu 18.04 Laptop, but my cross-compiler is ARM. Then I try to add parameter "-DBUILD_TESTING=0" in cmake command, it can skip unit test  and make shared-libraries successfully.

Thanks

**Comment by r3v3rt3d** [comment]
Hi,
Can you let me know how to setup my host to cross compile  avs smart screen sdk and apl library for arm64? 

Thanks in advance

**Comment by powj** [comment]
@r3v3rt3d Please refer to one of the quickstart guides referenced [here](https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/overview.html) for instructions on building the Alexa Smart Screen SDK, due to the large number of hardware combinations and toolchains we are unable provide instructions for devices beyond those included on that page. 
If you encounter a specific problem then I would recommend that you raise a new issue.

**Comment by r3v3rt3d** [comment]
Hi Pow,
Sorry but I can't find any guide for cross compile avs smart screen sdk and apl for arm64. Can you link me one pls? It's possible run this sdk on Android 9?

Thanks in advance.

**Comment by VaruPan** [comment]
Hi @r3v3rt3d,

As pointed by @powj, due to the large permutations of platforms+OS, we will not we able to provide build instructions of every platform. The closed platform to arm64 is [Raspberry Pi](https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html#raspberry-pi) reference platform. Please follow the instruction of the quick start guide.

Currently, Alexa Smart Screen SDK is officially supported on the platforms mentioned in the [overview](https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/overview.html) - namely - macOS, ubuntu and Raspberry Pi OS.
