### ISSUE TITLE
How to enable alexa wake word on macOS?

### ISSUE THREAD

**Issue by natchapol2347** [alexa/alexa-smart-screen-sdk#27]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
How do I enable alexa wake word in macOS, what do i need to put in cmake?

## What is the expected behavior?
use alexa hands free with no keyboard

## What behavior are you observing?
Hold A to talk

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ .] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ .] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by ereich1217** [comment]
You have to enable a wake word engine to do this hands free.  For the Mac I use Kitt.AI.

Here are the WW settings required:
https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#wake-word

**Comment by VaruPan** [comment]
Hi @natchapol2347, thanks for reaching out. Let us now if your question is resolved and we can close the issue.

P.S. Thanks @ereich1217

**Comment by VaruPan** [comment]
Closing the issue due to inactivity, please reopen the issue if unresolved. Thank you for your contribution to the Alexa Smart Screen SDK!

P.S. Here is the link to the WWE: https://github.com/Kitt-AI/snowboy
