### ISSUE TITLE
Notification Sound Cue doesn’t play on ss-sdk 2.0.2

### ISSUE THREAD

**Issue by yuan0258** [alexa/alexa-smart-screen-sdk#29]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

Notification Sound Cue doesn’t play (Base 244 / 246 / 247 / 248 /249 of AVS_Smart_functional_self-test_checklist_v2.5.9) on Smart Screen SDK 2.0.2.

We found notification sound cue doesn’t play because the parameter of FocusManager is difference with SDK 1.19.0.
For Smart Screen SDK 2.0.2 ,
[https://github.com/alexa/alexa-smart-screen-sdk/blob/c2196bef8adb1970a2bfd6572547e566468a77e9/modules/Alexa/ApplicationUtilities/SmartScreenClient/src/SmartScreenClient.cpp#L575](url)

```
    /*
     * Creating the Focus Manager - This component deals with the management of
     * layered audio focus across various
     * components. It handles granting access to Channels as well as pushing
     * different "Channels" to foreground,
     * background, or no focus based on which other Channels are active and the
     * priorities of those Channels. Each
     * Capability Agent will require the Focus Manager in order to request access
     * to the Channel it wishes to play on.
     */
    m_audioFocusManager =
        std::make_shared<afml::FocusManager>(afml::FocusManager::getDefaultAudioChannels(), m_audioActivityTracker);
```
 
For SDK 1.19.0,
[https://github.com/alexa/avs-device-sdk/blob/7da524a48664f85f3856cfc845ad44c8f68e02f3/ApplicationUtilities/DefaultClient/src/DefaultClient.cpp#L587](url)

```
    /*
     * Creating the Focus Manager - This component deals with the management of
     * layered audio focus across various
     * components. It handles granting access to Channels as well as pushing
     * different "Channels" to foreground,
     * background, or no focus based on which other Channels are active and the
     * priorities of those Channels. Each
     * Capability Agent will require the Focus Manager in order to request access
     * to the Channel it wishes to play on.
     */
    m_audioFocusManager = std::make_shared<afml::FocusManager>(
        afml::FocusManager::getDefaultAudioChannels(),
        m_audioActivityTracker,
        audioVirtualChannelConfiguration,
        interruptModel);
```

It seems the root cause it there is no audioVirtualChannelConfiguration when it create m_audioFocusManager.
Could you please confirm it?

## What is the expected behavior?

It should get notification sound when notification arrived 

## What behavior are you observing?

There is no notification sound when notification arrived 

## Provide the steps to reproduce the issue, if applicable:

Follow test case 244 / 246 / 247 / 248 /249 of AVS_Smart_functional_self-test_checklist_v2.5.9

### What version of the AVS Device SDK are you using?
      <1.19.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by nguymi91** [comment]
@yuan0258,

Thank you for submitting the ticket and including your initial investigation. 
We have root caused this issue, and we will fix it in upcoming releases.

Mike.
