### ISSUE TITLE
alexa smart screen sdk error

### ISSUE THREAD

**Issue by shubhamsbhosale96** [alexa/alexa-smart-screen-sdk#3]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

PA_ALSA_PLUGHW=1 ./modules/Alexa/SampleApp/src/SampleApp -C 
2019-11-27 09:34:43.912 [  1] I sdkVersion: 1.15.0
SmartScreenSDKVersion 2.0.1
No config specified for -C option       (this is an error)

### What version of the AVS Device SDK are you using?
      <1.15>

### Tell us what hardware you're using: raspberry pi
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version): Raspbian stretch
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by shubhamsbhosale96** [comment]
I resolved this issue

**Comment by bennyAv10** [comment]
Hi @shubhamsbhosale96,

When pasting multiple lines in the terminal, you should add backslash at the end of the lines to make them run as one command
```
 PA_ALSA_PLUGHW=1 ./modules/Alexa/SampleApp/src/SampleApp -C \
    /home/pi/sdk_folder/sdk-build/Integration/AlexaClientSDKConfig.json -C \
    /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/config/SmartScreenSDKConfig.json -L INFO
```

Thanks,
Benny
