### ISSUE TITLE
error while Downloading and building the Alexa Smart Screen SDK

### ISSUE THREAD

**Issue by shubhamsbhosale96** [alexa/alexa-smart-screen-sdk#36]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

first I run cmake command it works:
cmake -DCMAKE_PREFIX_PATH=$HOME/sdk_folder/sdk-install \
 -DWEBSOCKETPP_INCLUDE_DIR=$HOME/sdk_folder/third-party/websocketpp-0.8.1 \
 -DDISABLE_WEBSOCKET_SSL=ON \
 -DGSTREAMER_MEDIA_PLAYER=ON \
 -DCMAKE_BUILD_TYPE=DEBUG \
 -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$HOME/sdk_folder/third-party/portaudio/lib/.libs/libportaudio.a \
 -DPORTAUDIO_INCLUDE_DIR=$HOME/sdk_folder/third-party/portaudio/include/ \
 -DAPL_CORE=ON \
 -DAPLCORE_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/aplcore/include \
 -DAPLCORE_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/aplcore \
 -DYOGA_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/build/yoga-prefix/src/yoga \
 -DYOGA_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/lib \
  ../alexa-smart-screen-sdk

then while running make command:
Output is :
[ 98%] Building CXX object modules/Alexa/SampleApp/src/CMakeFiles/SampleApp.dir/PortAudioMicrophoneWrapper.cpp.o
[100%] Linking CXX executable SampleApp
[100%] Built target SampleApp
Scanning dependencies of target GUIClient
npm WARN gui@1.0.0 No repository field.
npm WARN gui@1.0.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

audited 507 packages in 90.152s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> gui@1.0.0 build /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js
> npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/sdk_folder/third-party/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true" "--define" "USE_UWP_CLIENT=false"

> gui@1.0.0 lint /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js
> tslint --project tsconfig.json -c tslint.json 'src/**/*.ts' 'src/**/*.tsx'

Hash: 2563335e17deb9bb2955
Version: webpack 4.44.1
Time: 37116ms
Built at: 03/08/2020 4:06:05 pm
 34 assets
Entrypoint main = main.bundle.js
 [1] /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/apl-client/index.js 607 KiB {0} [built]
 [4] ./lib/config/IDeviceAppConfig.ts 794 bytes {0} [built]
 [5] ./lib/messages/messages.ts 1.73 KiB {0} [built]
[10] ./lib/displayCards/AVSDisplayCardHelpers.ts 2.86 KiB {0} [built]
[11] ./main.tsx 563 bytes {0} [built]
[12] ./app.tsx 17.9 KiB {0} [built]
[25] ./lib/messages/NavigationEvent.ts 637 bytes {0} [built]
[26] ./lib/messages/client.ts 3.51 KiB {0} [built]
[30] ./lib/messages/sdkLogTransport.ts 1.7 KiB {0} [built]
[31] ./lib/focus/FocusManager.ts 3.03 KiB {0} [built]
[32] ./lib/activity/ActivityTracker.ts 2.38 KiB {0} [built]
[37] ./lib/config/GuiConfigHelpers.ts 8.14 KiB {0} [built]
[38] ./lib/messages/UWPClient.ts 1.67 KiB {0} [built]
[46] ./main.css 1.05 KiB {0} [built]
[47] ../node_modules/css-loader/dist/cjs.js!./main.css 735 bytes {0} [built]
    + 33 hidden modules

ERROR in /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,10)
      TS2305: Module '"/home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.

ERROR in /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,10)
      TS2305: Module '"/home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/sdk_folder/third-party/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true" "--define" "USE_UWP_CLIENT=false"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the gui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-08-03T10_36_06_428Z-debug.log
make[2]: *** [modules/GUI/CMakeFiles/GUIClient.dir/build.make:59: modules/GUI/CMakeFiles/GUIClient] Error 2
make[1]: *** [CMakeFiles/Makefile2:2468: modules/GUI/CMakeFiles/GUIClient.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

## What is the expected behavior?
Building done.

## What behavior are you observing?

make[2]: *** [modules/GUI/CMakeFiles/GUIClient.dir/build.make:59: modules/GUI/CMakeFiles/GUIClient] Error 2
make[1]: *** [CMakeFiles/Makefile2:2468: modules/GUI/CMakeFiles/GUIClient.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

## Tell us about your environment:
Raspberry pi 3 with raspbian buster.

### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:

- [ 1] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Other - tell us more: Raspbian buster

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by lynx-arul** [comment]
Thank you for bringing this to our attention!

It looks like [csstype](https://www.npmjs.com/package/csstype) did a major version bump and broke `import { VisibilityProperty } from 'csstype';` line in our code.

Went from [VisibilityProperty](https://raw.githubusercontent.com/frenic/csstype/v2/index.d.ts) to [Property.Visibility](https://github.com/frenic/csstype/blob/master/index.d.ts#L4878).

You can apply this fix to the code:
`type VisibilityProperty = import('csstype').Property.Visibility;` 
In both [APLRendererWindow](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/components/APLRendererWindow.tsx#L23) and [VoiceChrome](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/components/VoiceChrome.tsx#L7)


We will go ahead and update this fix in our next release.

Please let us know if you are still having issue.
Thanks again!

**Comment by yuan0258** [comment]
Another solution is used to old csstype version 2.6.3 in package.json
modules/GUI/js/package.json
@@ -23,6 +23,7 @@
     "source-map-loader": "^0.2.4",
     "loglevel": "^1.6.3",
     "react": "^16.4.1",
+    "csstype": "2.6.13",
     "react-dom": "^16.4.1",
     "style-loader": "^0.21.0",
     "ts-loader": "^4.4.1",

**Comment by shubhamsbhosale96** [comment]
@lynx-arul

Thanks.
It works.

**Comment by zalam003** [comment]
@lynx-arul I tried your recommendation.  Still getting the same error.  Can you provide the exact code? Thanks

**Comment by lynx-arul** [comment]
Hi Zalam, 
Please use the package-lock.json that powj has provided [in this link.](https://github.com/alexa/alexa-smart-screen-sdk/issues/41)

Please feel free to re-open this ticket if this did not fix your issue.
PS: Make sure to delete any existing package-lock and node_module before running the cmake.

**Comment by zalam003** [comment]
Thanks for the information.  I will take a look at it.
