### ISSUE TITLE
I want to get output response of alexa in text format

### ISSUE THREAD

**Issue by shubhamsbhosale96** [alexa/alexa-smart-screen-sdk#37]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

I am using raspberry pi 3b. I want to control rpi pins by alexa assistant. I don't want to use IoT service, it takes more time to perform action of triggering pins. I have tried with alexa-pi, IFTTT and adafruit IoT server.
Is there any solution to get alexa speaking response in text, so I can compare text with my different triggers.

## What is the expected behavior?

Is there any option to access that alexa output response in text.
I will create an alexa skill that will provide me my expected output.
I don't want to use AWS lambda with AWS IoT service, it costly after 1 year free tier.

## What behavior are you observing?

I also tried with flask ask service and ngrok service. It doesn't works well. Every time when system restarts, ngrok address changes. So, every time we need to set address manually.

### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:

- [ ] Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Other - tell us more: Raspbian Buster

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by chemudug-amzn** [comment]
Hello @shubhamsbhosale96 - Have you looked at the captions interface? Enabling captions will allow you to generate captions for TTS content. Please refer to the following to get context on captions: https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/features.html#captions
