### ISSUE TITLE
make error: has no exported member 'VisibilityProperty'.

### ISSUE THREAD

**Issue by alexareactnative1** [alexa/alexa-smart-screen-sdk#38]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
I am going to build alexa smart screen sdk. But it shows the error.
I build avs device sdk and apl core successfully. 

## What is the expected behavior?
build success

## What behavior are you observing?
[100%] Linking CXX executable SampleApp
[100%] Built target SampleApp
Scanning dependencies of target GUIClient
npm WARN gui@1.0.0 No repository field.
npm WARN gui@1.0.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 507 packages in 1.681s
found 0 vulnerabilities

> gui@1.0.0 build /home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js
> npm run lint && webpack --config webpack.config.js "--output-path" "/home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/buildmmsdk/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true" "--define" "USE_UWP_CLIENT=false"

> gui@1.0.0 lint /home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js
> tslint --project tsconfig.json -c tslint.json 'src/**/*.ts' 'src/**/*.tsx'

Hash: 6b7dc179ef6edbab6cfb
Version: webpack 4.44.1
Time: 3042ms
Built at: 08/06/2020 11:07:21 AM
 34 assets
Entrypoint main = main.bundle.js
 [1] /home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/apl-client/index.js 607 KiB {0} [built]
 [4] ./lib/config/IDeviceAppConfig.ts 794 bytes {0} [built]
 [5] ./lib/messages/messages.ts 1.73 KiB {0} [built]
[10] ./lib/displayCards/AVSDisplayCardHelpers.ts 2.86 KiB {0} [built]
[11] ./main.tsx 563 bytes {0} [built]
[12] ./app.tsx 17.9 KiB {0} [built]
[25] ./lib/messages/NavigationEvent.ts 637 bytes {0} [built]
[26] ./lib/messages/client.ts 3.51 KiB {0} [built]
[30] ./lib/messages/sdkLogTransport.ts 1.7 KiB {0} [built]
[31] ./lib/focus/FocusManager.ts 3.03 KiB {0} [built]
[32] ./lib/activity/ActivityTracker.ts 2.38 KiB {0} [built]
[37] ./lib/config/GuiConfigHelpers.ts 8.14 KiB {0} [built]
[38] ./lib/messages/UWPClient.ts 1.67 KiB {0} [built]
[46] ./main.css 1.05 KiB {0} [built]
[47] ../node_modules/css-loader/dist/cjs.js!./main.css 735 bytes {0} [built]
    + 33 hidden modules

ERROR in /home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,10)
      TS2305: Module '"/home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.

ERROR in /home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,10)
      TS2305: Module '"/home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/ANT.AMAZON.COM/shanshen/Documents/VestelAmbientHome/buildmmsdk/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true" "--define" "USE_UWP_CLIENT=false"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the gui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ANT.AMAZON.COM/shanshen/.npm/_logs/2020-08-06T18_07_21_484Z-debug.log
modules/GUI/CMakeFiles/GUIClient.dir/build.make:57: recipe for target 'modules/GUI/CMakeFiles/GUIClient' failed
make[2]: *** [modules/GUI/CMakeFiles/GUIClient] Error 2
CMakeFiles/Makefile2:2153: recipe for target 'modules/GUI/CMakeFiles/GUIClient.dir/all' failed
make[1]: *** [modules/GUI/CMakeFiles/GUIClient.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

## Provide the steps to reproduce the issue, if applicable:
cmake steps

### What version of the AVS Device SDK are you using?
      <1.20.0>

### Tell us what hardware you're using:
- [X ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [X ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [x ] The issue is not applicable to the AVS Device SDK SampleApp.
- [x ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by lynx-arul** [comment]
Hi @alexareactnative1,
  Thanks for reaching us for this issue. We have noted this before and provided a patch release [v2.2.1](https://github.com/alexa/alexa-smart-screen-sdk/releases/tag/v2.2.1). Please let us know if you are still having issue with this patch.

Thanks.

**Comment by chemudug-amzn** [comment]
Closing - please reach out to us if you still have issues.
