### ISSUE TITLE
Typo in Instructions

### ISSUE THREAD

**Issue by Piflyer** [alexa/alexa-smart-screen-sdk#4]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Typo in instructions
## Provide the steps to reproduce the issue, if applicable:

Instructions should be ` cd /home/pi/sdk_folder/ss-build
    PA_ALSA_PLUGHW=1 ./modules/Alexa/SampleApp/src/SampleApp -C  \
    /home/pi/sdk_folder/sdk-build/Integration/AlexaClientSDKConfig.json -C \
    /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/config/SmartScreenSDKConfig.json -L INFO` Not ` cd /home/pi/sdk_folder/ss-build
    PA_ALSA_PLUGHW=1 ./modules/Alexa/SampleApp/src/SampleApp -C 
    /home/pi/sdk_folder/sdk-build/Integration/AlexaClientSDKConfig.json -C
    /home/pi/sdk_folder/alexa-smart-screen-sdk/modules/GUI/config/SmartScreenSDKConfig.json -L INFO`.
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

**Comment by bennyAv10** [comment]
Hi @Piflyer,

Are you referring to the backslashes on the end of lines? If so, that can be useful for coppy&paste. We'll update the instructions. Thanks for raising this!

Benny
