### ISSUE TITLE
AplCoreConnectionManager::handleBuild

### ISSUE THREAD

**Issue by zhtqfkj** [alexa/alexa-smart-screen-sdk#40]
![image](https://user-images.githubusercontent.com/99098/90096248-56727b00-dd65-11ea-8f75-62f1ad860e36.png)

**Comment by VaruPan** [comment]
Hi @zhtqfkj,

Good catch, thanks for pointing it out. We will update this for the next release.

Thank you for your contribution to the Alexa Smart Screen SDK!
Varun
