### ISSUE TITLE
Error during install alexa-smart-screen-sdk

### ISSUE THREAD

**Issue by anfo030** [alexa/alexa-smart-screen-sdk#42]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
During the installation of the smart screen sdk an error occurs.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x ] Other - tell us more: Raspian buster

i have entered this command.: 
sudo /home/pi/DIY-Echo-Show/scripts/alexa-screen-installer.sh  

##############
100% tests passed, 0 tests failed out of 38

Total Test time (real) =  30.45 sec

The following tests did not run:
	 39 - VisualCharacteristicsTest.testGetCapabilityConfigurations (Disabled)
[ 38%] Built target unit
[ 45%] Built target Communication
[ 54%] Built target SmartScreenClient
[100%] Built target SampleApp
npm WARN gui@1.0.0 No repository field.
npm WARN gui@1.0.0 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

added 505 packages from 333 contributors and audited 510 packages in 23.948s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> gui@1.0.0 build /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js
> npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/DIY-Echo-Show/Alexa/ss-build/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true"

> gui@1.0.0 lint /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js
> tslint --project tsconfig.json -c tslint.json 'src/**/*.ts' 'src/**/*.tsx'

Hash: 9b73c69ad62534392812
Version: webpack 4.44.1
Time: 19377ms
Built at: 2020-09-08 17:59:07
                                                               Asset       Size  Chunks             Chunk Names
                                                    ../dist/app.d.ts   3.56 KiB          [emitted]  
                           ../dist/components/APLRendererWindow.d.ts   2.41 KiB          [emitted]  
                            ../dist/components/PlayerInfoWindow.d.ts    1.7 KiB          [emitted]  
                                  ../dist/components/SampleHome.d.ts  383 bytes          [emitted]  
                                 ../dist/components/VoiceChrome.d.ts  848 bytes          [emitted]  
                             ../dist/lib/activity/ActivityEvent.d.ts  554 bytes          [emitted]  
                           ../dist/lib/activity/ActivityTracker.d.ts   1.09 KiB          [emitted]  
                            ../dist/lib/config/GuiConfigHelpers.d.ts  944 bytes          [emitted]  
                            ../dist/lib/config/IDeviceAppConfig.d.ts   4.12 KiB          [emitted]  
        ../dist/lib/config/visualCharacteristics/IDeviceDisplay.d.ts   1.08 KiB          [emitted]  
        ../dist/lib/config/visualCharacteristics/IDisplayWindow.d.ts  963 bytes          [emitted]  
      ../dist/lib/config/visualCharacteristics/IInteractionMode.d.ts  515 bytes          [emitted]  
                ../dist/lib/config/visualCharacteristics/IVideo.d.ts  114 bytes          [emitted]  
../dist/lib/config/visualCharacteristics/IVisualCharacteristics.d.ts  655 bytes          [emitted]  
          ../dist/lib/config/visualCharacteristics/IWindowState.d.ts  354 bytes          [emitted]  
                 ../dist/lib/displayCards/AVSDisplayCardHelpers.d.ts    1.9 KiB          [emitted]  
                                  ../dist/lib/focus/ChannelName.d.ts  343 bytes          [emitted]  
                                 ../dist/lib/focus/FocusManager.d.ts   2.05 KiB          [emitted]  
                                ../dist/lib/focus/FocusResource.d.ts  296 bytes          [emitted]  
                                   ../dist/lib/focus/FocusState.d.ts  183 bytes          [emitted]  
                             ../dist/lib/focus/IChannelObserver.d.ts  251 bytes          [emitted]  
                                 ../dist/lib/focus/IFocusBridge.d.ts  248 bytes          [emitted]  
                               ../dist/lib/media/AVSAudioPlayer.d.ts   1.38 KiB          [emitted]  
                                     ../dist/lib/media/AVSVideo.d.ts   1.43 KiB          [emitted]  
                           ../dist/lib/messages/NavigationEvent.d.ts  333 bytes          [emitted]  
                                    ../dist/lib/messages/client.d.ts   1.75 KiB          [emitted]  
                                  ../dist/lib/messages/messages.d.ts   4.28 KiB          [emitted]  
                           ../dist/lib/messages/sdkLogTransport.d.ts  842 bytes          [emitted]  
                                        ../dist/lib/utils/timer.d.ts  235 bytes          [emitted]  
                                                   ../dist/main.d.ts   21 bytes          [emitted]  
                                4444bbbc2f4dd0a9586f053308ab9a1a.png   22.7 KiB          [emitted]  
                                                          index.html  187 bytes          [emitted]  
                                                      main.bundle.js   4.23 MiB    main  [emitted]  main
Entrypoint main = main.bundle.js
[../../apl-client/index.js] /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/apl-client/index.js 613 KiB {main} [built]
[../node_modules/css-loader/dist/cjs.js!./main.css] 735 bytes {main} [built]
[./app.tsx] 16.6 KiB {main} [built]
[./lib/activity/ActivityEvent.ts] 883 bytes {main} [built]
[./lib/activity/ActivityTracker.ts] 2.39 KiB {main} [built]
[./lib/config/GuiConfigHelpers.ts] 7.92 KiB {main} [built]
[./lib/config/IDeviceAppConfig.ts] 799 bytes {main} [built]
[./lib/displayCards/AVSDisplayCardHelpers.ts] 2.82 KiB {main} [built]
[./lib/focus/FocusManager.ts] 3.03 KiB {main} [built]
[./lib/messages/NavigationEvent.ts] 642 bytes {main} [built]
[./lib/messages/client.ts] 3.51 KiB {main} [built]
[./lib/messages/messages.ts] 1.74 KiB {main} [built]
[./lib/messages/sdkLogTransport.ts] 1.7 KiB {main} [built]
[./main.css] 1.05 KiB {main} [built]
[./main.tsx] 568 bytes {main} [built]
    + 33 hidden modules

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/DIY-Echo-Show/Alexa/ss-build/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the gui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-08T15_59_07_882Z-debug.log
make[2]: *** [modules/GUI/CMakeFiles/GUIClient.dir/build.make:59: modules/GUI/CMakeFiles/GUIClient] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:2152: modules/GUI/CMakeFiles/GUIClient.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
###############################

THANKS for Help!

**Comment by powj** [comment]
Hi, please ensure you have pulled the latest version of the code - this issue was resolved in our [2.2.1](https://github.com/alexa/alexa-smart-screen-sdk/releases/tag/v2.2.1) release (#38).

Note that you may encounter the issue mentioned in #41 after this, a workaround is available in that issue (https://github.com/alexa/alexa-smart-screen-sdk/issues/41#issuecomment-687335928) and will be resolved in our next release.
