### ISSUE TITLE
Build the Alexa Smart Screen SDK [WARNING]

### ISSUE THREAD

**Issue by shipishi** [alexa/alexa-smart-screen-sdk#49]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
cmake -DCMAKE_PREFIX_PATH=$HOME/sdk_folder/sdk-install \
 -DWEBSOCKETPP_INCLUDE_DIR=$HOME/sdk_folder/third-party/websocketpp-0.8.1 \
 -DDISABLE_WEBSOCKET_SSL=ON \
 -DGSTREAMER_MEDIA_PLAYER=ON \
 -DCMAKE_BUILD_TYPE=DEBUG \
 -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$HOME/sdk_folder/third-party/portaudio/lib/.libs/libportaudio.so \
 -DPORTAUDIO_INCLUDE_DIR=$HOME/sdk_folder/third-party/portaudio/include/ \
 -DAPL_CORE=ON \
 -DAPLCORE_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/aplcore/include \
 -DAPLCORE_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/aplcore \
 -DAPLCORE_RAPIDJSON_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/build/rapidjson-prefix/src/rapidjson/include \
 -DYOGA_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/build/yoga-prefix/src/yoga \
 -DYOGA_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/lib \
 ../alexa-smart-screen-sdk

Result:
Creating the build directory for the AlexaModule with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the CapabilityAgents with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the ApplicationUtilities with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the APLClient with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the Communication with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the SmartScreenClient with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the SampleApp with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
Creating the build directory for the Utils with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
Creating the build directory for the SSSDKCommon with build type: DEBUG
No keyword detector type specified, skipping build of keyword detector.
Bluetooth implementation not supported
-- Configuring done
WARNING: Target "AlexaPresentationTest" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "TemplateRuntimeTest" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "VisualCharacteristicsTest" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SampleApp" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SmartScreenCaptionStateManagerTest" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "SmartScreenCaptionPresenterTest" requests linking to directory "/usr/local/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/sw/sdk_folder/third-party

### What version of the AVS Device SDK are you using?
      <1.20.1>

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by zsubas** [comment]
Hi,

Thank you for bringing this issue to our attention. We'll address it in the future.

Meanwhile, please let me know if you are having any other issues with installation of SSSDK.

**Comment by jason-amzn** [comment]
closing, please reopen if required
