### ISSUE TITLE
alexa smart screen sdk with SSL enabled not working

### ISSUE THREAD

**Issue by Jagadish-Bommisetty** [alexa/alexa-smart-screen-sdk#52]
## Briefly summarize your issue:
i have build smart screen sdk on Ubuntu 18.04. SDK versions are smart screen sdk -> 2.2.1 and avs sdk -> 1.20.1. while building SS-SDK, i enabled the SSL with -DDISABLE_WEBSOCKET_SSL=OFF flag. i generated the keys and certs with method given in code base(https://github.com/alexa/alexa-smart-screen-sdk/blob/v2.2.1/modules/GUI/config/certificates/generate.sh). i kept the keys in directory where i ran the sampleApp and given those paths in SmartSmartSDKConfig.json file. when i run the sample app, i don't see the index.html page showing content. it is stuck at "Configuring Device..". Any configuration need to done in GUI components for SSL? and in generate.sh, client cert and keys are genered. How to use them?. i have attached the SmartScreenSDKConfig.json and logs with debug9. i also attached the sample certificate and keys what i generated.

## What is the expected behavior?
index.html need to establish a connection and get the content

## What behavior are you observing?
html file stuck at "Configuring Device..". In inspect of browser, seen that trying for wss connection.

## Provide the steps to reproduce the issue, if applicable:
Build the SS-SDK  with -DDISABLE_WEBSOCKET_SSL=OFF. Generate the keys with specified script. Give path for keys and cert in SmartScreenSDKConfig.json. provide the json while running sampleApp.

## Tell us about your environment:
Ubuntu->18.04
smart screen sdk->2.2.1
apl core -> 1.3.3
firefox-> 81.0
### What version of the AVS Device SDK are you using?
      1.20.1

### Tell us what hardware you're using:
- [ ] Desktop / Laptop

### Tell us about your OS (Type & version):
- [ ] Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
[issueWithSSL_Enable.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/5372488/issueWithSSL_Enable.zip)

**Comment by zsubas** [comment]
Please make sure you are following the steps below for enabling ssl:

- certificate variables in the SmartScreenSDKConfig.json needs to have full path of the certificates
```
"websocketCertificateAuthority":"<sdk_directory>/modules/GUI/config/certificates/ca.cert",
"websocketCertificate":"<sdk_directory>/modules/GUI/config/certificates/server.chain",
"websocketPrivateKey":"<sdk_directory>/modules/GUI/config/certificates/server.key"
```
- add certificates to Firefox by following steps below:
1. In Firefox go to Preferences.
2. In the left panel, choose Privacy & Security.
3. Go to Security → Certificates, and click View Certificates.
4. Under Your Certificates, import client.p12.
5. Under Authorities, import ca.cert.
6. Navigate to https://localhost:8933
7. Select your certificate when prompted

In addition, please refer to security requirements page to get more information: https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/security-requirements.html

**Comment by Jagadish-Bommisetty** [comment]
Thanks for quick response. it is working after adding client.p12 which i missed.

**Comment by Jagadish-Bommisetty** [comment]
@zsubas , After adding certificates in chrome browser like above mentioned. it stuck at configuring Device... But same certificates and same build is working fine in firefox. In chrome console, Error message seen,  "**WebSocket connection to 'wss://localhost:8933/' failed: WebSocket opening handshake was canceled**. i have attached the debug9 logs and screenshot of chrome console.
![consoleError_chrome](https://user-images.githubusercontent.com/72811995/98233836-940e2b00-1f85-11eb-954c-a743b2e8c60b.png)
[websocket_ssl.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/5493915/websocket_ssl.zip)

**Comment by lynx-arul** [comment]
Is it possible to ensure that your certificates are valid? It is a little strange that it works on Firefox but not Chrome.

**Comment by Jagadish-Bommisetty** [comment]
**same certificates** i have used in **Firefox** and it is **working fine**. i am attaching the certificates which are used for testing. These certificates are generated with generate.sh script provided in alexa smart screen sdk git [ https://github.com/alexa/alexa-smart-screen-sdk/blob/v2.2.1/modules/GUI/config/certificates/generate.sh ]. Is there any specific changes for chrome browser.
[cert_amazon.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/5498473/cert_amazon.zip)

**Comment by vkarpuram** [comment]
Hello @Jagadish-Bommisetty - Could you please try the following troubleshooting steps: 

1. Ensure that you have used absolute paths when pointing to the certificates  in your SmartScreenSDKConfig.json file
2. Verify that a dialog pops up on chrome asking you to trust the MMSDK_Client_Cert when you navigate to: https://localhost:8933
3. In your chromium browser, navigate to Settings -> Advanced->Privacy and Security -> Manage Certificates and select Authorities. Here you should see a certificate by org-Amazon. Please make sure that this cert does not show UNTRUSTED. If it does, Trust the cert and try again

Please let us know if this resolves your issues.

**Comment by Jagadish-Bommisetty** [comment]
@vkarpuram it is working. In Manage certificates -> your certificates, still showing UNTRUSTED.

**Comment by vkarpuram** [comment]
Hello @Jagadish-Bommisetty,

That's great to hear. However I highly recommend using your own trusted certificates for your production code. This is just a sample implementation.

Please reach out if you face any additional issues.
