### ISSUE TITLE
Alexa Screen SDK on Raspberry Pi - TuneIn stopped working - streamingError 

### ISSUE THREAD

**Issue by alexwala** [alexa/alexa-smart-screen-sdk#53]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Since couple of days tuneIn stopped working on Alexa Screen SDK on raspberry pi.

## What is the expected behavior?
Alexa Screen SDK on raspberry pi should play tuneIn radio station.

## What behavior are you observing?
After telling Alexa to play radio station , she is answering : 'playing radio station from tuneIn' but nothing happens.

## Provide the steps to reproduce the issue, if applicable:
Tell Alexa to play radio station

### What version of the AVS Device SDK are you using?
      2.2.0

### Tell us what hardware you're using:
- [x] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [x] Other - tell us more:
Raspbian Buster
Windows 64-bit

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.
- [x] The issue IS APPLICABLE to the AVS Device SDK SampleApp, see:
[Alexa SDK on raspberry pi - tuneIn stopped working](https://github.com/alexa/avs-device-sdk/issues/1808)

**Comment by jason-amzn** [comment]
closing in favor of https://github.com/alexa/avs-device-sdk/issues/1808
