### ISSUE TITLE
enabling the voice chrome

### ISSUE THREAD

**Issue by shawnpaffhausen** [alexa/alexa-smart-screen-sdk#54]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

I have a very good working alexa smart screen with wakeword enabled.. Like to add the voice chrome element for the state. I can see all the parts of it the tsx and css file and know it's part of the gui client just need some direction in enabling it

**Comment by jason-amzn** [comment]
Hello,

Please confirm that you do see the state displayed in the bottom right corner - "IDLE", "LISTENING", etc 
That is the voice chrome released with Alexa Smart Screen SDK, and is enabled by default

For further questions and other resources, please reach out via https://developer.amazon.com/alexa/console/contact-us

**Comment by shawnpaffhausen** [comment]
Yes i have that I'm talking about the visual bar..all the coding is there just not sure which switch to throwSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: jason-amzn <notifications@github.com> Date: 10/19/20  18:57  (GMT-05:00) To: alexa/alexa-smart-screen-sdk <alexa-smart-screen-sdk@noreply.github.com> Cc: shawnpaffhausen <shawnpaffhausen@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [alexa/alexa-smart-screen-sdk] enabling the voice chrome (#54) 
Hello,
Please confirm that you do see the state displayed in the bottom right corner - "IDLE", "LISTENING", etc
That is the voice chrome released with Alexa Smart Screen SDK, and is enabled by default
For further questions and other resources, please reach out via https://developer.amazon.com/alexa/console/contact-us
