### ISSUE TITLE
AVS shoppling list display fail

### ISSUE THREAD

**Issue by eytu0233** [alexa/alexa-smart-screen-sdk#60]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Alexa doesn’t list all of items. It only responses the number of items in shopping list and doesn't show the display card.

## What is the expected behavior?
Alexa responses all of items in shopping list and shows the display card. But the smart screen sdk v2.3 is ok

## What behavior are you observing?
As same as summary. However, we could not reproduce on Echo Show with the same account.

Ex:
Avs-device-sdk reply: You have five items in shopping list. Buy milk. Buy car ….etc
Alexa-smart-screen-sdk: You have five items in shopping list(No speaking list detail information.)

## Provide the steps to reproduce the issue, if applicable:
1.	Run smart screen sdk v2.4 on RPi4.
2.	Say ‘Alexa, what's on my shopping list?’
3.	The device only reply the numbers of shopping list information. No detail inform show in UI and TTS

### What version of the AVS Device SDK are you using?
      AVS Device SDK: <1.21.0>
      APL core library: <1.4.1>
      Alexa smart screen SDK: <2.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [*] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by powj** [comment]
Hi, Thank you for raising this. 

We are aware of an issue which currently results in AVS devices supporting APL to not receive lists correctly and we are tracking this internally. Once the issue has been resolved devices should once again receive lists without requiring any code changes.
