### ISSUE TITLE
The UI didn't update after thumbs up on Amazon Music.

### ISSUE THREAD

**Issue by eytu0233** [alexa/alexa-smart-screen-sdk#61]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
The UI didn't update after thumbs up on Amazon Music.

## What is the expected behavior?
The UI will update and anti-white the thumbs up icon after thumbs up command.

## What behavior are you observing?
As same as summary. Even Alexa responsed ‘Got it’, the UI didn't update and anti-white the thumbs up icon.
However, we DID NOT reproduce this issue on Pandora.

## Provide the steps to reproduce the issue, if applicable:
1.	Run smart screen sdk v2.4 on RPi4.
2.	Say ‘Alexa, play the easy pop station on Prime’.
3.	Wait the music and screen ready.
4.	Say ‘Alexa, thumbs up’.
5.	Alexa responses ‘Got it’.

### What version of the AVS Device SDK are you using?
      AVS Device SDK: <1.21.0>
      APL core library: <1.4.1>
      Alexa smart screen SDK: <2.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [*] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by powj** [comment]
Hi, Thank you for raising this issue - unfortunately the Alexa Smart Screen SDK does not receive any notification that the Thumbs Up/Down status has changed if a voice command is used so it is not possible for the UI to be updated in this case.

We are aware of this issue and are working with partner teams to improve the experience but are unable to provide any timeline for potential fixes.
