### ISSUE TITLE
The ALEXA UI doesn't synchronize audio when playing music.

### ISSUE THREAD

**Issue by eytu0233** [alexa/alexa-smart-screen-sdk#62]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
The ALEXA UI doesn't synchronize audio when playing music.

## What is the expected behavior?
The ALEXA UI synchronizes audio when playing music as soon as possible.

## What behavior are you observing?
After stopping the first time music play, we waited few minutes for screen refresh.
Then asked Alexa to start music play once again.
The ALEXA UI didn't display the playcard until the audio had played about 10 seconds.

Does this behavior match your expectation?

The log is that we recorded after stopping music play.
[sssdk240_playmusic_after.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/5663979/sssdk240_playmusic_after.zip)

## Provide the steps to reproduce the issue, if applicable:
1.	Run smart screen sdk v2.4 on RPi4.
2.	Say ‘Alexa, play music’. Play music the first time.
3.	Say ‘Alexa, stop’.
4.	Wait 5 minutes.
5.	Say ‘Alexa, play music’. Play music the second time.
6.	Record the time interval between audio and playcard.

### What version of the AVS Device SDK are you using?
      AVS Device SDK: <1.21.0>
      APL core library: <1.4.1>
      Alexa smart screen SDK: <2.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [*] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by VaruPan** [comment]
Hi @eytu0233,

Alexa-smart-screen-sdk receives [RenderPlayerInfo](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/templateruntime.html#renderplayerinfo) presentation directive in addition to [Play](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/audioplayer.html#play) directive from AVS asynchronously. Due to this, there may be a delay in the presentation processing and rendering, especially on platform with low processing power.

Thank you for your contribution to the Alexa Smart Screen SDK!

**Comment by yuan0258** [comment]
Hi @VaruPan,

We found the  RenderPlayerInfo and Play directive almost send to device simultaneously

2020-12-09 05:45:10.515 [  2] I DirectiveSequencer:onDirective:directive=namespace\:AudioPlayer\,name\:Play\,messageId\:2d5964c5-1e6e-44a3-b7f0-6fcb772619cf\,dialogRequestId\:f6059e5b-484a-4b4d-9e4c-0e6b85389387\,correlationToken\:\,eventCorrelationToken\:\,payloadVersion\:\,instance\:

2020-12-09 05:45:10.508 [  2] I DirectiveSequencer:onDirective:directive=namespace\:TemplateRuntime\,name\:RenderPlayerInfo\,messageId\:69834d84-fb60-4478-b650-84dcb45ddb00\,dialogRequestId\:f6059e5b-484a-4b4d-9e4c-0e6b85389387\,correlationToken\:\,eventCorrelationToken\:\,payloadVersion\:\,instance\:

But the UI still be too late. How could we know about presentation processing and rendering time delay?

**Comment by VaruPan** [comment]
Sure,

**Comment by yuan0258** [comment]
Hi @VaruPan,
1. Does the render time is about 17.728s on RPi4? It doesn't make sense why it take too long time
2020-12-09 05:45:10.511 [  c] 5 TemplateRuntime:handleRenderPlayerInfoDirective
2020-12-09 05:45:28.239 [  2] 3 GUILogBridge:GUILog:component=WSClient:message sent, type: renderComplete

2.How to use MetricsRecorder to record it?
