### ISSUE TITLE
Can not play specific program from TuneIn

### ISSUE THREAD

**Issue by eytu0233** [alexa/alexa-smart-screen-sdk#63]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
Can not play specific program from TuneIn

## What is the expected behavior?
Play specific program from TuneIn normally.

## What behavior are you observing?
According to the certification document, we tried to test TuneIn Program feature.
(TuneInCertificationChecklist_05_03_2019.xlsx)
However, Alexa did not play any audio nor playcard after "Here is rachel maddow show from TuneIn" reply.
But Alexa could play radio from TuneIn.

Here is the log.
[sssdk240_tuneIn.zip](https://github.com/alexa/alexa-smart-screen-sdk/files/5664335/sssdk240_tuneIn.zip)

## Provide the steps to reproduce the issue, if applicable:
1.	Run smart screen sdk v2.4 on RPi4.
2.	Say ‘Alexa, play the program rachel maddow show on TuneIn’.

### What version of the AVS Device SDK are you using?
      AVS Device SDK: <1.21.0>
      APL core library: <1.4.1>
      Alexa smart screen SDK: <2.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [*] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by VaruPan** [comment]
Hi @eytu0233, 

Thanks a lot for reaching out. Can you please verify if you are not hitting the same issue on AVS Device SDK? We have a known [issue](https://github.com/alexa/avs-device-sdk/issues/1808)  that was recently fixed on device SDK and will be available in future releases.

Thank you for your contribution to the Alexa Smart Screen SDK!
