### ISSUE TITLE
Requested 'AlexaClientSDK = 1.21.0' but version of AlexaClientSDK is 1.22.0

### ISSUE THREAD

**Issue by tigger-gg** [alexa/alexa-smart-screen-sdk#66]
Hello ,

I'm new to the alexa thing. 
Until December 9th I had no problem to configure cmake. But today the following error appears:
`pi@AlexaRPi:~/sdk_folder/ss-build $ cmake -DCMAKE_PREFIX_PATH=$HOME/sdk_folder/sdk-install \
> -DCMAKE_PREFIX_PATH=$HOME/sdk_folder/sdk-install \
> -DSENSORY_KEY_WORD_DETECTOR=ON \
> -DSENSORY_KEY_WORD_DETECTOR_LIB_PATH=/home/pi/sdk_folder/third-party/alexa-rpi/lib/libsnsr.a \
> -DSENSORY_KEY_WORD_DETECTOR_INCLUDE_DIR=/home/pi/sdk_folder/third-party/alexa-rpi/include \
> -DWEBSOCKETPP_INCLUDE_DIR=$HOME/sdk_folder/third-party/websocketpp-0.8.1 \
> -DDISABLE_WEBSOCKET_SSL=ON \
> -DGSTREAMER_MEDIA_PLAYER=ON \
> -DCMAKE_BUILD_TYPE=DEBUG \
> -DPORTAUDIO=ON -DPORTAUDIO_LIB_PATH=$HOME/sdk_folder/third-party/portaudio/lib/.libs/libportaudio.a \
> -DPORTAUDIO_INCLUDE_DIR=$HOME/sdk_folder/third-party/portaudio/include/ \
> -DAPL_CORE=ON \
> -DAPLCORE_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/aplcore/include \
> -DAPLCORE_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/aplcore \
> -DAPLCORE_RAPIDJSON_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/build/rapidjson-prefix/src/rapidjson/include \
> -DYOGA_INCLUDE_DIR=$HOME/sdk_folder/apl-core-library/build/yoga-prefix/src/yoga \
> -DYOGA_LIB_DIR=$HOME/sdk_folder/apl-core-library/build/lib \
> -DBLUETOOTH_BLUEZ_PULSEAUDIO_OVERRIDE_ENDPOINTS=ON -DBLUETOOTH_BLUEZ=ON \
>  ../alexa-smart-screen-sdk
-- Checking for module 'AlexaClientSDK=1.21.0'
--   Requested 'AlexaClientSDK = 1.21.0' but version of AlexaClientSDK is 1.22.0
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:452 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:622 (_pkg_check_modules_internal)
  modules/Alexa/CMakeLists.txt:7 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/pi/sdk_folder/ss-build/CMakeFiles/CMakeOutput.log".`

What can I do to solve this issue?
I use a Raspberry Pi 4 with the latest Raspbian.
Sorry for my english, it's not my native language.
Thanks in advance.

**Comment by VaruPan** [comment]
@tigger-gg,

Thanks a lot for reaching out to Alexa team. It seems that you are on incorrect version of avs-device-sdk (1.22.0) that was released [5 days ago](https://github.com/alexa/avs-device-sdk/tags).

Here is the error:
`-- Requested 'AlexaClientSDK = 1.21.0' but version of AlexaClientSDK is 1.22.0`

Go to avs-device-sdk and checkout [version 1.21.0](https://github.com/alexa/avs-device-sdk/tree/v1.21.0) and rebuild. You will need to do a make install for the new binaries.
