### ISSUE TITLE
How to profile APL document download and render performance?

### ISSUE THREAD

**Issue by yuan0258** [alexa/alexa-smart-screen-sdk#68]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

Base on issue #62
Sure, the best way to profile the rendering time is by profiling the time between `TemplateRuntime::handleRenderPlayerInfoDirective` and `GUIClient::executeHandleRenderComplete`. Alternatively, you can use [MetricsRecorder](https://github.com/alexa/avs-device-sdk/blob/master/Metrics/MetricRecorder/src/MetricRecorder.cpp).

Please open the ticket if you have any further questions.  Thanks!

_Originally posted by @VaruPan in https://github.com/alexa/alexa-smart-screen-sdk/issues/62#issuecomment-744901341_

We want to know about how to profile several things
1.How to profile APL document download time from user say uttrance?
2.Browser rendering performance
3.How to use MetricsRecorder to record it?

## What is the expected behavior?

Browser rending UI fast as soon as possible

## What behavior are you observing?

Browser rending UI to slow in first time.

APL document for browser rendering time too long
Log:https://github.com/alexa/alexa-smart-screen-sdk/files/5663979/sssdk240_playmusic_after.zip

Does the render time is about 17.728s on RPi4.
It doesn't make sense why it take too long time
2020-12-09 05:45:10.511 [ c] 5 TemplateRuntime:handleRenderPlayerInfoDirective
2020-12-09 05:45:28.239 [ 2] 3 GUILogBridge:GUILog:component=WSClient:message sent, type: renderComplete

## Provide the steps to reproduce the issue, if applicable:

Run smart screen sdk v2.4 on RPi4.
Say ‘Alexa, play music’. Play music the first time.
Say ‘Alexa, stop’.
Wait 5 minutes.
Say ‘Alexa, play music’. Play music the second time.
Record the time interval between audio and playcard.

### What version of the AVS Device SDK are you using?
    AVS Device SDK: <1.21.0>
    APL core library: <1.4.1>
    Alexa smart screen SDK: <2.4.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [*] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [*] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [*] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by yuan0258** [comment]
Could we measure from Thinking to TemplateRuntime:handleRenderPlayerInfoDirective about 1.38s for APL download time ?
2020-12-09 05:45:09.131 [ 17] 5 TemplateRuntime:onDialogUXStateChanged:state=THINKING
2020-12-09 05:45:10.511 [ c] 5 TemplateRuntime:handleRenderPlayerInfoDirective
2020-12-09 05:45:28.239 [ 2] 3 GUILogBridge:GUILog:component=WSClient:message sent, type: renderComplete

**Comment by powj** [comment]
Hi @yuan0258 ,
It is possible to enable metrics for tracking APL performance within the Smart Screen SDK, however by default this functionality is not enabled. If you are primarily interested in APL metrics then it should be possible to add this by making a few small modifications (note that this metrics sink is provided as a sample for testing purposes only):

1. Rebuild and reinstall the AVS Device SDK with the `-DMETRICS=ON` [flag](https://developer.amazon.com/en-US/docs/alexa/avs-device-sdk/cmake-parameters.html#metrics) 
2. Modify the Smart Screen SDK code to use the Sample metrics sink
   Add the following includes to SmartScreenClient.cpp
```
#include <Metrics/MetricRecorder.h>
#include <Metrics/SampleMetricSink.h>
```
  Replace the null metrics recorder found at https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/Alexa/ApplicationUtilities/SmartScreenClient/src/SmartScreenClient.cpp#L478 with the Sample implementation
```
    std::string metricsFilePath{"/tmp/metrics.dmp"};
    std::unique_ptr<alexaClientSDK::metrics::implementations::SampleMetricSink> fileSink{
        new alexaClientSDK::metrics::implementations::SampleMetricSink(metricsFilePath)};
    auto metricRecorder = alexaClientSDK::metrics::implementations::MetricRecorder::createMetricRecorderInterface(std::move(fileSink));
```

3. Rebuild the Smart Screen SDK adding the metrics and APL metrics flags `-DMETRICS=ON -DUSE_APL_TELEMETRY=ON`
4. When running the SampleApp, metrics can be found in the path provided above i.e. `/tmp/metrics.dmp`

**Comment by VaruPan** [comment]
Closing the ticket due to inactivity, please feel free to open the ticket again. Once again, thanks a lot for contributing to Alexa Smart Screen SDK!

**Comment by yuan0258** [comment]
@powj,
I following your step to enable -DMETRICS=ON -DUSE_APL_TELEMETRY=ON in Smart Screen SDK.
It seems it could create /tmp/metric.dmp
But there is no timpstamp information in /tmp/metric file.
