### ISSUE TITLE
Playing Amazon Music failed to display matadata on the timestamp on v2.1

### ISSUE THREAD

**Issue by yuan0258** [alexa/alexa-smart-screen-sdk#69]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

The timestamp can be display correctly on SSSDK v2.4 but not on v2.1.
We cloudn't upgrade version from v2.1 to v2.4 for MP purpose.
How could we get the patch for this issue only?

## What is the expected behavior?

UI show timestamp information corretly
v2.4
![v2 4_ok](https://user-images.githubusercontent.com/2118320/102972328-d4c20380-4535-11eb-9705-151259928e84.png)
v2.1
![SDK_1 19 1_SSSDK_2 1](https://user-images.githubusercontent.com/2118320/102977960-b1e81d00-453e-11eb-8e78-505f3a68b407.jpg)

## Provide the steps to reproduce the issue, if applicable:

Play amazon music on device

### What version of the AVS Device SDK are you using?
      AVS Device SDK: <1.19.1>
      APL core library: <1.3.3>
      Alexa smart screen SDK: <2.1.0>

### Tell us what hardware you're using:
- [] Desktop / Laptop
- [*] Raspberry Pi
- [] Other - tell us more:

### Tell us about your OS (Type & version):
- [*] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [*] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by zsubas** [comment]
Hello,

Thank you for reaching out!

Time/Length support for player info card introduced at version 2.3: https://github.com/alexa/alexa-smart-screen-sdk/releases/tag/v2.3.0

Unfortunately, we don't have a specific patch for supporting this on 2.1, in order to get this future you need to use 2.3 or above.

**Comment by yuan0258** [comment]
@zsubas,

Thanks for your reply. 
One more question abouot it. 
Which module(apl-core-library or ss-sdk) will impact this issue?

**Comment by zsubas** [comment]
Hey yuan0258,

In this scenario both affects. apl-core provides the APL (which contains the length information). Smart screen sdk parses this information and display it on the screen.

**Comment by yuan0258** [comment]
Hi zsubas,
OK. We are trying to find Amazon QA team to negotiated this issue.
Thanks for your reply

**Comment by vkarpuram** [comment]
Closing out this issue as there is no further action required from our end. Please let us know if you need additional assistance

**Comment by yuan0258** [comment]
@vkarpuram,

We need to re-open this issue because Amazon QA team couldn't waiver this issue.
