### ISSUE TITLE
When try "show my kindle books", it doesn't show UI and only output audio

### ISSUE THREAD

**Issue by oscar1372** [alexa/alexa-smart-screen-sdk#75]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

For test case Base 520~522 on AVS_Smart_functional_self-test_checklist_v2.9.7, It doesn't show any UI when we try "show my kindle books" as test expected.

Here is log,
[show_my_kindle_book_noui_debug9.log](https://github.com/alexa/alexa-smart-screen-sdk/files/5836697/show_my_kindle_book_noui_debug9.log)

## What is the expected behavior?

According test case expected, UI show be show. (as Echo show or FireTV)

## What behavior are you observing?

It only audio output which alexa response "You have XXX books...."

## Provide the steps to reproduce the issue, if applicable:

1.  Buy some kindle books
2. Say "Show my kindle books"

### What version of the AVS Device SDK are you using?
      <1.21.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [x] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by powj** [comment]
Hi @oscar1372 ,

This is the expected behavior and should not be blocking certification. Kindle currently does not support a Template Runtime or APL experience so only a speech response is expected.

If you have any further questions feel free to either re-open this issue or open a new issue.
