### ISSUE TITLE
When Announcement received, it only response audio and doesn't have display card

### ISSUE THREAD

**Issue by oscar1372** [alexa/alexa-smart-screen-sdk#77]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

For test case 601, the expected result should show display card on GUI device but it doesn't show on Smart Screen SDK.

## What is the expected behavior?

Show Announcement display card and response.

## What behavior are you observing?

Only response annoucement

## Provide the steps to reproduce the issue, if applicable:

0. Raspberry Pi / Alexa App / Echo Show use same account.
1. Raspberry Pi is online and announcement support. 
2. Use Alexa App or other echo show to make an announcement. 
(Raspberry Pi will receive announcement to response) 

### What version of the AVS Device SDK are you using?
      <1.21.0>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [x] Raspberry Pi
- [ ] Other - tell us more:

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [x] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [x] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by VaruPan** [comment]
Hi @oscar1372,

Announcements are currently supported as an audio-only experience on Alexa Smart Screen SDK. So the display card is not supported.

We have noted your interest for this functionality and are continuously working on improving the Smart Screen SDK, however we cannot comment on when a specific feature may be available.

Thanks a lot for reaching out and contributing to Alexa Smart Screen SDK.

**Comment by oscar1372** [comment]
@VaruPan Thanks your response. Yes, I am checking the test case of functional self-test checklist and found it needs to show display card on GUI device(TV).

Could I know whether certification will be impact when SDK only support audio-only experience?

**Comment by VaruPan** [comment]
You can reach out to the certification team to get more information on waivers for unavailable UX.
