### ISSUE TITLE
The device screen width is 1026 and the height is 600; how to configure SmartScreenSDKConfig.json

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#83]
"gui": {
    "appConfig": {
      "description": "Philips Smart Speaker",
      "mode": "HUB",
      "emulateDisplayDimensions": true,
      "scaleToFill": true,
      "audioInputInitiator": "WAKEWORD",
      "windows": [
        {
          "id": "hubLandscape",
          "templateId": "hubLandscape",
          "sizeConfigurationId": "landscape",
          "interactionMode": "hub",
          "theme": "dark",
          "animationQuality": "normal"
        }
      ],
      "defaultWindowId": "hubLandscape",
      "deviceKeys": {
        "talkKey": {
          "code": "KeyA",
          "keyCode": 65,
          "key": "a"
        },
        "backKey": {
          "code": "KeyB",
          "keyCode": 66,
          "key": "b"
        },
        "exitKey": {
          "code": "Escape",
          "keyCode": 27,
          "key": "Escape"
        }
      }
    },
    "visualCharacteristics": [
      {
        "type": "AlexaInterface",
        "interface": "Alexa.Display",
        "version": "1.0",
        "configurations": {
          "display": {
            "type": "PIXEL",
            "touch": [ "SINGLE" ],
            "shape": "RECTANGLE",
            "dimensions": {
              "resolution": {
                "unit": "PIXEL",
                "value": {
                  "width": 1060,
                  "height": 600
                }
              },
              "densityIndependentResolution": {
                "unit": "DP",
                "value": {
                  "width": 1060,
                  "height": 600
                }
              },
              "pixelDensity": {
                "unit": "DPI",
                "value": 160
              },
              "physicalSize": {
                "unit": "INCHES",
                "value": {
                  "width": 8.6,
                  "height": 5.4
                }
              }
            }
          }
        }
      },
      {
        "type": "AlexaInterface",
        "interface": "Alexa.Display.Window",
        "version": "1.0",
        "configurations": {
          "templates": [
            {
              "id": "hubLandscape",
              "type": "STANDARD",
              "configuration": {
                "sizes": [
                  {
                    "type": "DISCRETE",
                    "id": "landscape",
                    "value": {
                      "unit": "PIXEL",
                      "value": {
                        "width": 1060,
                        "height": 600
                      }
                    }
                  }
                ],
                "interactionModes": [
                  "hub"
                ]
              }
            }
          ]
        }
      },
      {
        "type": "AlexaInterface",
        "interface": "Alexa.InteractionMode",
        "version": "1.0",
        "configurations": {
          "interactionModes": [
            {
              "id": "hub",
              "uiMode": "HUB",
              "interactionDistance": {
                "unit": "INCHES",
                "value": 84
              },
              "touch": "SUPPORTED",
              "keyboard": "UNSUPPORTED",
              "video": "SUPPORTED"
            }
          ]
        }
      },
      {
        "type": "AlexaInterface",
        "interface": "Alexa.Presentation.APL.Video",
        "version": "1.0",
        "configurations": {
          "video": {
            "codecs": [
              "H_264_42",
              "H_264_41"
            ]
          }
        }
      }
    ]
  }

**Comment by gaoseng** [comment]
how to configure SmartScreenSDKConfig.json and The display can completely cover the screen

**Comment by vkarpuram** [comment]
Hello @gaoseng,

Thank you for reaching out to us. You can find information regarding the configuration here: https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/config/SmartScreenSDKConfig.md

As for the display size, please take a look at the section titled Visual Characteristics Parameters. It seems like you would like to change the dimensions under Alexa.Display.

If you are having further trouble with this. Please fill out the information requested when creating a new issue as this will help us understand what to provide help with. Specifically, it would be helpful to know more about your device as well as the expected behavior vs. actual behavior

**Comment by vkarpuram** [comment]
Closing this out due to inactivity. Please reopen this issue if you face further trouble with the configuration.
