### ISSUE TITLE
alexa-smart-screen-sdk-2.6.0  Compilation failed due to tslint error in /modules/GUI

### ISSUE THREAD

**Issue by cdelsordo** [alexa/alexa-smart-screen-sdk#88]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
We are upgrading our alexa-device avs sdk to 1.23, alexa smart-screen-assistant sdk to 2.6.0 and aplcore to 1.5.1 so we can begin integration work on Alexa HD music.  We are running into a build error similar to one we saw with alexa smart-screen-assistant 2.2.x.   There is a  tslint error as in /modules/GUI.  The temporary fix was provided via  a customized package_lock.json file. We then moved to alexa smart-screen-assistant 2.3.0 which did not require the work around. The build time generated package_lock.json worked in that release.   Our build system use npm: 6.14.10 and node: v12.20.1.
We are working with Amazon on integrating several features on the CommScope smd7852 custom HW.

## What is the expected behavior?
All sdks normally build without an issue.

## What behavior are you observing?
We are experiencing the following build error:
FAILED: modules/Alexa/ApplicationUtilities/SmartScreenClient/src/libSmartScreenClient.so
| : && /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/sysroots/x86_64-linux/usr/bin/arm-rdk-linux-gnueabi/arm-rdk-linux-gnueabi-g++ -fPIC -march=armv7ve -mthumb -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a15   --sysroot=/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/sysroots/smd7852  -Os -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0=/usr/src/debug/alexa-mm/2.6.0-r0 -fdebug-prefix-map=/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/sysroots/x86_64-linux= -fdebug-prefix-map=/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/sysroots/smd7852=   -fvisibility-inlines-hidden  -march=armv7ve -mthumb -mfpu=neon  -mfloat-abi=hard -mcpu=cortex-a15   --sysroot=/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/sysroots/smd7852 -DDEBUG -DACSDK_DEBUG_LOG_ENABLED -Wall -Wsign-compare -g -DRAPIDJSON_HAS_STDSTRING  -Wl,--disable-new-dtags -shared -Wl,-soname,libSmartScreenClient.so -o modules/Alexa/ApplicationUtilities/SmartScreenClient/src/libSmartScreenClient.so modules/Alexa/ApplicationUtilities/SmartScreenClient/src/CMakeFiles/SmartScreenClient.dir/ConnectionRetryTrigger.cpp.o modules/Alexa/ApplicationUtilities/SmartScreenClient/src/CMakeFiles/SmartScreenClient.dir/DefaultClientComponent.cpp.o modules/Alexa/ApplicationUtilities/SmartScreenClient/src/CMakeFiles/SmartScreenClient.dir/DeviceSettingsManagerBuilder.cpp.o modules/Alexa/ApplicationUtilities/SmartScreenClient/src/CMakeFiles/SmartScreenClient.dir/EqualizerRuntimeSetup.cpp.o modules/Alexa/ApplicationUtilities/SmartScreenClient/src/CMakeFiles/SmartScreenClient.dir/StubApplicationAudioPipelineFactory.cpp.o modules/Alexa/ApplicationUtilities/SmartScreenClient/src/CMakeFiles/SmartScreenClient.dir/SmartScreenClient.cpp.o  -Wl,-rpath,/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/Alexa/SmartScreenCapabilityAgents/TemplateRuntime/src:/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/Alexa/SmartScreenCapabilityAgents/AlexaPresentation/src:/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/Alexa/SmartScreenCapabilityAgents/VisualCharacteristics/src:/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/Alexa/APLClientLibrary/APLClient/src: modules/Alexa/SmartScreenCapabilityAgents/TemplateRuntime/src/libSmartScreenTemplateRunTime.so -lacsdkAlerts -lacsdkAudioPlayer -lacsdkBluetooth -lacsdkDoNotDisturb -lacsdkEqualizer -lacsdkEqualizerImplementations -lacsdkExternalMediaPlayer -lacsdkExternalMediaPlayerInterfaces -lacsdkMultiRoomMusic -lacsdkNotifications -lacsdkCBLAuthorizationDelegate -lacsdkDefaultDeviceSettingsManager -lacsdkDefaultInternetConnectionMonitor -lacsdkDefaultSampleApplicationOptions -lacsdkLibcurlAlexaCommunications -lacsdkLibcurlHTTPContentFetcher -lacsdkNullMetricRecorder -lacsdkNullSystemTimeZone -lacsdkSampleApplicationCBLAuthRequester -lacsdkNullBluetoothImplementation -lacsdkGstreamerApplicationAudioPipelineFactory -lAVSCommon -lACL -lADSL -lAFML -lCaptionsComponent -lCaptions -lCaptionsLib -lacsdkCore -lacsdkPostConnectOperationProviderRegistrar -lacsdkSystemClockMonitor -lAVSGatewayManager -lCertifiedSender -lEndpoints -lDeviceSettings -lContextManager -lCapabilitiesDelegate -lInterruptModel -lPlaylistParser -lKWD -lAMAZONLITE -lKeywordDetectorProvider -lAIP -lAlexa -lApiGateway -lInteractionModel -lPlaybackController -lSoftwareComponentReporter -lSpeakerManager -lSpeechSynthesizer -lAVSSystem -lTemplateRuntime -lCBLAuthDelegate -lDefaultClient -lAudioResources -lSystemSoundPlayer -lSDKComponent -lMediaPlayer -lRegistrationManager -lacsdkManufactory -lacsdkShared -lacsdkShutdownManager -lacsdkStartupManager -lSpeechEncoder -lSQLiteStorage -lSynchronizeStateSender -lcurl -lsqlite3 -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -L/lib modules/Alexa/SmartScreenCapabilityAgents/AlexaPresentation/src/libAlexaPresentation.so modules/Alexa/SmartScreenCapabilityAgents/VisualCharacteristics/src/libVisualCharacteristics.so -lCallManager modules/Alexa/APLClientLibrary/APLClient/src/libAPLClient.so -Wl,-Bstatic -lapl -lyogacore -Wl,-Bdynamic -lacsdkAlerts -lacsdkAudioPlayer -lacsdkBluetooth -lacsdkDoNotDisturb -lacsdkEqualizer -lacsdkEqualizerImplementations -lacsdkExternalMediaPlayer -lacsdkExternalMediaPlayerInterfaces -lacsdkMultiRoomMusic -lacsdkNotifications -lacsdkCBLAuthorizationDelegate -lacsdkDefaultDeviceSettingsManager -lacsdkDefaultInternetConnectionMonitor -lacsdkDefaultSampleApplicationOptions -lacsdkLibcurlAlexaCommunications -lacsdkLibcurlHTTPContentFetcher -lacsdkNullMetricRecorder -lacsdkNullSystemTimeZone -lacsdkSampleApplicationCBLAuthRequester -lacsdkNullBluetoothImplementation -lacsdkGstreamerApplicationAudioPipelineFactory -lAVSCommon -lACL -lADSL -lAFML -lCaptionsComponent -lCaptions -lCaptionsLib -lacsdkCore -lacsdkPostConnectOperationProviderRegistrar -lacsdkSystemClockMonitor -lAVSGatewayManager -lCertifiedSender -lEndpoints -lDeviceSettings -lContextManager -lCapabilitiesDelegate -lInterruptModel -lPlaylistParser -lKWD -lAMAZONLITE -lKeywordDetectorProvider -lAIP -lAlexa -lApiGateway -lInteractionModel -lPlaybackController -lSoftwareComponentReporter -lSpeakerManager -lSpeechSynthesizer -lAVSSystem -lTemplateRuntime -lCBLAuthDelegate -lDefaultClient -lAudioResources -lSystemSoundPlayer -lSDKComponent -lMediaPlayer -lRegistrationManager -lacsdkManufactory -lacsdkShared -lacsdkShutdownManager -lacsdkStartupManager -lSpeechEncoder -lSQLiteStorage -lSynchronizeStateSender -lcurl -lsqlite3 -lgstapp-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -L/lib && :
| /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/sysroots/x86_64-linux/usr/libexec/arm-rdk-linux-gnueabi/gcc/arm-rdk-linux-gnueabi/6.4.0/ld: error: cannot find -lCallManager
| collect2: error: ld returned 1 exit status
| [4/4] cd /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js && npm install && npm run build -- --output-path /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/GUI --env DISABLE_WEBSOCKET_SSL=true --env USE_UWP_CLIENT=false
| FAILED: modules/GUI/CMakeFiles/GUIClient
| cd /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js && npm install && npm run build -- --output-path /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/GUI --env DISABLE_WEBSOCKET_SSL=true --env USE_UWP_CLIENT=false
| npm WARN gui@1.0.0 No repository field.
| npm WARN gui@1.0.0 license should be a valid SPDX license expression
|
| audited 376 packages in 3.584s
| found 0 vulnerabilities
|
|
| > gui@1.0.0 build /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js
| > npm run lint && webpack --config webpack.config.js "--output-path" "/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/GUI" "--env" "DISABLE_WEBSOCKET_SSL=true" "--env" "USE_UWP_CLIENT=false"
|
|
| > gui@1.0.0 lint /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js
| > tslint --project tsconfig.json -c tslint.json 'src/**/*.ts' 'src/**/*.tsx'
|
| [webpack-cli] SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid escape
|     at pathToArgumentName (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack/lib/cli.js:66:4)
|     at addFlag (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack/lib/cli.js:170:16)
|     at traverse (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack/lib/cli.js:243:21)
|     at traverse (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack/lib/cli.js:299:23)
|     at traverse (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack/lib/cli.js:248:24)
|     at Object.getArguments (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack/lib/cli.js:308:2)
|     at WebpackCLI.getBuiltInOptions (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack-cli/lib/webpack-cli.js:584:47)
|     at loadCommandByName (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack-cli/lib/webpack-cli.js:725:38)
|     at Command.program.action (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack-cli/lib/webpack-cli.js:1255:23)
|     at Command.listener [as _actionHandler] (/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/alexa-smart-screen-sdk-2.6.0/modules/GUI/js/node_modules/webpack-cli/node_modules/commander/index.js:922:31)
| npm ERR! code ELIFECYCLE
| npm ERR! errno 2
| npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build/modules/GUI" "--env" "DISABLE_WEBSOCKET_SSL=true" "--env" "USE_UWP_CLIENT=false"`
| npm ERR! Exit status 2
| npm ERR!
| npm ERR! Failed at the gui@1.0.0 build script.
| npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
|
| npm ERR! A complete log of this run can be found in:
| npm ERR!     /home/cdelsordo/.npm/_logs/2021-04-21T18_14_40_594Z-debug.log
| ninja: build stopped: subcommand failed.
| WARNING: /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/temp/run.do_compile.16562:1 exit 1 from 'eval ${DESTDIR:+DESTDIR=${DESTDIR} }VERBOSE=1 cmake --build '/export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/build' "$@" -- -j 10'
| ERROR: Function failed: do_compile (log file is located at /export/cdelsordo/RDKV-531_ALEXA/build-smd7852/tmp/work/cortexa15t2hf-neon-rdk-linux-gnueabi/alexa-mm/2.6.0-r0/temp/log.do_compile.16562)
 

## Provide the steps to reproduce the issue, if applicable:
After building alexa-device 1.23 and aplcore 1.6 we are trying to build alexa smart-screen-assistant version 2.6

## Tell us about your environment:
alexa-device 1.23 and aplcore 1.6 we are trying to build alexa smart-screen-assistant version 2.6. Our build system use npm: 6.14.10 and node: v12.20.1.

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ x] Other - tell us more:

CommScope smd7852 which uses Broadcom bcm72180 chip (same as Broadcom reference board you use)

### Tell us about your OS (Type & version):
- [ x] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:
Same as Broadcom bcm72180 reference board.  URSR 20.2

### Have you tried the same use case with AVS Device SDK SampleApp?
- [x ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by sngoc-amazon** [comment]
Hi @cdelsordo,

Thanks for bringing this issue to our attention. Can you please verify the that you are using apl-core-library v1.5.1 (https://github.com/alexa/apl-core-library/tree/v1.5.1)?

Can you also please share the cmake command you are using to build avs-device-sdk and alexa-smart-screen-sdk?

**Comment by aginesh** [comment]
Hi @sngoc-amazon,
   I also ran into the same tslint error mentioned above.
Using smart screen sdk v2.6, device sdk v1.23 and apl-core 1.5.1
Please find attached the cmake commands and the error logs.
[device-sdk-cmake.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6364125/device-sdk-cmake.txt)
[smartscreen-sdk-cmake.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6364127/smartscreen-sdk-cmake.txt)
[errorlog.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6364128/errorlog.txt)

**Comment by sngoc-amazon** [comment]
Hi @aginesh,

I'm unable to reproduce this issue on my end. Since alexa-smart-screen-sdk v2.5 release, there has been numerous upgrades to GUI SampleApp dependencies, including upgrade webpack version. Can you try to remove alexa-smart-screen-sdk/modules/GUI/js/node_modules folder and rebuild and see if you are still experiencing the same issue?

**Comment by cdelsordo** [comment]
> Hi @cdelsordo,
> 
> Thanks for bringing this issue to our attention. Can you please verify the that you are using apl-core-library v1.5.1 (https://github.com/alexa/apl-core-library/tree/v1.5.1)?
> 
> Can you also please share the cmake command you are using to build avs-device-sdk and alexa-smart-screen-sdk?

So yes - I have tried it with aplcore 1.5.1.  I checked further and my yocto build system is actually using nodejs 8.xx which is not compliant - the build system uses the roots version and not the build servers version version as I previously stated.  I believe this is causing an issue.  So I am trying to upgrade nodejs to 10.16.3 in my roots.  By the way I checked alexa-smart-screen 2.5 has the same issue.  It does not occur with alexa-smart-screen 2.3.  this likely due to Webcli JS changes. Just, FYI - I am working with Jay Patel (avs solutions eng?) from your team trying to get ready to integrate HD Music and Video Conferencing on our device which is why I need alexa smart screen 2.6 for video conferencing.

**Comment by cdelsordo** [comment]
> Hi @sngoc-amazon,
> I also ran into the same tslint error mentioned above.
> Using smart screen sdk v2.6, device sdk v1.23 and apl-core 1.5.1
> Please find attached the cmake commands and the error logs.
> [device-sdk-cmake.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6364125/device-sdk-cmake.txt)
> [smartscreen-sdk-cmake.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6364127/smartscreen-sdk-cmake.txt)
> [errorlog.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6364128/errorlog.txt)

Check out what version of nodejs you have in your build.  My version is not compliant.  Also we need to have Amazon put a check in their CMakeLists.txt to check for this and throw clear exception.

**Comment by cdelsordo** [comment]
Closed issue by mistake sorry!

**Comment by cdelsordo** [comment]
We would like to suggest that the CMakeLists.txt for alexa smart screen checks for compliant nodejs version and throw a clear exception if it is not compliant.

**Comment by sngoc-amazon** [comment]
Hi @cdelsordo,

We recommend upgrading to node 12.x.x or above (https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/package.json#L7). Please remove alexa-smart-screen-sdk/modules/GUI/js/node_modules directory before building. Please update if this is able to resolve your issue.

We are looking into your suggestion and encourage you to check future releases for updates on this.

**Comment by cdelsordo** [comment]
We have made a change to use the proper version of nodejs and this issue is resolved. We will close this ticket thank you for the support.
