### ISSUE TITLE
No audio response for some queries

### ISSUE THREAD

**Issue by aginesh** [alexa/alexa-smart-screen-sdk#89]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
For queries that have a visual response, there is no audio response.
Ex query 1: Alexa, how is the weather today?
Weather update can be seen on screen, but there is no audio feedback. (logs attached for this query)
[alexa_smart_screen_sdk_query_logs.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6430219/alexa_smart_screen_sdk_query_logs.txt)

Ex query 2: Alexa, what is the capital of Italy?
Italy's capital is seen on screen, but there is no audio feedback.

## What is the expected behavior?
There should be both audio and visual feedback.

## What behavior are you observing?
For queries that do not have a visual response, there is an audio response.
Ex query 3: Alexa, what is the time.
There is audio feedback for this query.
But for queries of type 1 and 2 mentioned above, there is no audio response.

## Provide the steps to reproduce the issue, if applicable:
Issue a command that has both audio and visual responses. Ex: Alexa, how is the weather today.
There would only be a visual response and no audio response.

## Tell us about your environment:
smartscreen SDK v2.6.0
device sdk v1.23
apl core version: 1.5.1

### Tell us what hardware you're using:
Raspberry Pi

### Tell us about your OS (Type & version):
- [ ] Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
The issue is not applicable to the AVS Device SDK SampleApp.

**Comment by zsubas** [comment]
Hello @aginesh,

I'm not able to reproduce this issue on my end. Which debug level you are using? Can you please use DEBUG9 and share a new log?

**Comment by aginesh** [comment]
The attached logs are using debug9.

**Comment by zsubas** [comment]
The interesting thing is I don't see any SpeechSynthesizer commands from your logs, are these logs contain the case when speech works e.g. "time"? 

Can you please add this flag to your cmakes and reprdouce the issue again: -DACSDK_EMIT_SENSITIVE_LOGS=ON.  Please make sure you are including both cases visual and no-visual.

**Note: If you have ACSDK_EMIT_SENSITIVE_LOGS flags enabled and your printout contains sensitive information like user name, client ID, or refresh token, please remove those from the logs before submitting an issue.**

**Comment by aginesh** [comment]
[acsdk_logs_with_debug9_startup_no_commands.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6437910/acsdk_logs_with_debug9_startup_no_commands.txt)
[acsdk_logs_with_debug9_with_audio_response.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6437915/acsdk_logs_with_debug9_with_audio_response.txt)
[acsdk_logs_with_debug9_no_audio_weather_query.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6437916/acsdk_logs_with_debug9_no_audio_weather_query.txt)

**Comment by longryan** [comment]
which version of the smart screen config are you using?
For instance, the[ sample TV Overlay](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/config/guiConfigSamples/GuiConfigSample_TvOverlayLandscape.json#L88) config leverages the [dialog:UNSUPPORTED](https://developer.amazon.com/en-US/docs/alexa/alexa-voice-service/interaction-mode.html) feature for the overlay window, communicating to the responding Alexa service that they should not return dialog.

**Comment by aginesh** [comment]
I was using the TV overlay sample.
After changing the dialog:UNSUPPORTED to SUPPORTED, there was an audio response as expected.
