### ISSUE TITLE
Question on hardware video resource management with Smart Screen SDK

### ISSUE THREAD

**Issue by PhilippeGrave** [alexa/alexa-smart-screen-sdk#91]
## Briefly summarize your issue:
While watching a TV channel, end-user may invoke Alexa to launch a skill that plays some video contents. On device with constrained resources and a single hardware video decoder (e.g. STB), live channel playback must be stopped prior to grant Skill / APL access to video hardware decoder to play the video content.

## What is the expected behaviour?
An handshake should take place between the smart-screen SDK and the device firmware for the smart-screen SDK to request the video resource and for the firmware to release the video resource and acknowledge video resource release to the Smart-Screen SDK. 

## Question
We haven't seen any mechanism in the the smart-screen SDK to do so but we may have miss it. 
Is there a mean to implement such mechanism with the latest smart-screen SDK ? If not, is it something planned in smart-screen SDK roadmap? 

Thanks.

**Comment by rpalkar-amzn** [comment]
Hi @PhilippeGrave 

Thank you for reaching out. The current implementation of video component used for APL can be found in [AVSVideo.ts](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/lib/media/AVSVideo.ts). It is responsible for acquiring/releasing focus by communicating with the C++ [SampleApp](https://github.com/alexa/alexa-smart-screen-sdk/tree/master/modules/Alexa/SampleApp) based on playback state.

> An handshake should take place between the smart-screen SDK and the device firmware for the smart-screen SDK to request the video resource and for the firmware to release the video resource and acknowledge video resource release to the Smart-Screen SDK.

By handshake between smart-screen SDK and device firmware, are you referring to handshake between the GUI JS application that runs in a browser and C++ SampleApp? Is the video playback being considered in a browser environment?

**Comment by PhilippeGrave** [comment]
Hi @rpalkar-amzn 
Thanks for your feedback and for pointing out AVSVideo.ts file: it looks like that either "Content" or "Dialog" channel focus needs to be acquired before playback is actually started.
By handshake, I mean this exact same focus acquisition mechanism but on a channel dedicated to "Video" so that playback is actually granted / started by the GUI JS application, only if the "video" channel focus has been acquired, i.e. only if the hardware video decoder has been released (if previously used for live channel playback for instance). Does it make sense ?

**Comment by rpalkar-amzn** [comment]
Hi @PhilippeGrave 

Thank you for the reply. For more clarity, does below sequence represent the ask correctly?
```
GUI JS app -> C++ SampleApp : acquireVideoResource
C++ SampleApp -> GUI JS app : videoResourceAvailable

GUI JS app plays video.
Video playback ends.

GUI JS app -> C++ SampleApp : releaseVideoResource
C++ SampleApp -> GUI JS app : videoResourceReleased
```

One approach to implement this would be extending [AVSVideo class](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/lib/media/AVSVideo.ts#L66) and overriding [onEvent](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/lib/media/AVSVideo.ts#L88), [play](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/lib/media/AVSVideo.ts#L116) methods to send messages from the GUI app for acquiring/releasing video resource. A factory class for this video component similar to [AVSVideoFactory](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/lib/media/AVSVideo.ts#L42) will have to be specified in [APLRendererWindow.tsx](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/GUI/js/src/components/APLRendererWindow.tsx#L258). 

Corresponding changes will be required in [GUIClient](https://github.com/alexa/alexa-smart-screen-sdk/blob/master/modules/Alexa/SampleApp/src/GUI/GUIClient.cpp) to handle messages received from GUI app based on your requirements.

**Comment by rpalkar-amzn** [comment]
Hi @PhilippeGrave 

Thank you for the confirmation. Please let us know if the suggested approach works for you or if you need further guidance on implementing the same.
