### ISSUE TITLE
How to display the tell me joke page correctly

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#95]
##  When the screen width is 800px and the height is 1280px, how to make the tell me joke page full screen and rotate the screen, re-call the init method of aplClient, the tell me joke page scrolling parameters are reported wrong.

**Comment by VaruPan** [comment]
Hi @gaoseng,

I do not fully understand the question here. If this is about scrolling APL presentation after screen rotation, the rendering layer provided with current version of Alexa Smart Screen SDK currently does not support screen rotations.

Thanks,
Varun

P.S. Can you please use the bug template attached below to report an issue? 
```
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).


## Briefly summarize your issue:
<!--- Provide a more detailed introduction to the issue itself, and why you consider it to be a bug -->

## What is the expected behavior?
<!--- Tell us what should happen -->

## What behavior are you observing?
<!--- Tell us what's happening instead -->

## Provide the steps to reproduce the issue, if applicable:
<!--- Provide the steps for reproduce -->

## Tell us about your environment:
<!--- Include as many relevant details about the environment you experienced the bug in -->
### What version of the AVS Device SDK are you using?
      <x.y.z>

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [ ] Other - tell us more:


### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [ ] Other - tell us more:

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.
```

**Comment by gaoseng** [comment]
> Hi @gaoseng,
> 
> I do not fully understand the question here. If this is about scrolling APL presentation after screen rotation, the rendering layer provided with current version of Alexa Smart Screen SDK currently does not support screen rotations.
> 
> Thanks,
> Varun
> 
> P.S. Can you please use the bug template attached below to report an issue?
> 
> ```
> **IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).
> 
> 
> ## Briefly summarize your issue:
> 
> 
> ## What is the expected behavior?
> 
> 
> ## What behavior are you observing?
> 
> 
> ## Provide the steps to reproduce the issue, if applicable:
> 
> 
> ## Tell us about your environment:
> 
> ### What version of the AVS Device SDK are you using?
>       <x.y.z>
> 
> ### Tell us what hardware you're using:
> - [ ] Desktop / Laptop
> - [ ] Raspberry Pi
> - [ ] Other - tell us more:
> 
> 
> ### Tell us about your OS (Type & version):
> - [ ] Linux
> - [ ] MacOS 
> - [ ] Raspbian Stretch
> - [ ] Raspbian Jessy
> - [ ] Other - tell us more:
> 
> ### Have you tried the same use case with AVS Device SDK SampleApp?
> - [ ] The issue is not applicable to the AVS Device SDK SampleApp.
> - [ ] The issue is not reproducible on the AVS Device SDK SampleApp.
> ```
OK
