### ISSUE TITLE
it's can't display correctly when I render the twice with joke page

### ISSUE THREAD

**Issue by gaoseng** [alexa/alexa-smart-screen-sdk#96]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:
 - the version is 2.6

## What is the expected behavior?
- when I rotate the device and I call the method of createRenderer to render the page the  joke page , the page can display correctly

## What behavior are you observing?
- when I rotate the device and I call the method of createRenderer to render the Page of  the  joke page, But this page is not scrollingand the console prompt that cannot read property 'scrollToRectInComponent' of undefined

## Provide the steps to reproduce the issue, if applicable:
- I can't,because I change you code

## Tell us about your environment:
 - 
### What version of the AVS Device SDK are you using?
   - 2.6

### Tell us what hardware you're using:
- Desktop / Laptop

### Tell us about your OS (Type & version):
- Linux

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp. 
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by chemudug-amzn** [comment]
Hi,

We do not support screen rotation at this time. Since you are modifying the code it is difficult to advice on how best to proceed. If you have any specific questions about our code base - please do ask them and we can advise you.
