### ISSUE TITLE
crash and leaks on logout

### ISSUE THREAD

**Issue by rom-vdb** [alexa/alexa-smart-screen-sdk#97]
## Briefly summarize your issue:
We are integrating smart screen sdk in STB and are testing some logout/login scenarios, crash happens after less than 8 iterations

## What is the expected behavior?
We would want to allow infinite logout/login

## What behavior are you observing?
We are calling the m_guiManager->resetDevice() function that provokes the logout algorithm and we have quite quickly a crash between 1 to 8 logout/login iteration(s)
we observe leaks in SmartScreen SampleApp at the same time (MediaPlayer WorkerLoop and GuiClient serverThreads threads are increasing and RSS is increasing)

## Provide the steps to reproduce the issue, if applicable:
logout/login several times

## Tell us about your environment:
we are integrating smart screen sdk in a set top box 
smart screen sdk 2.6.0
avs 1.23.0
apl 1.5.1
websocketpp 0.8.2

### Tell us what hardware you're using:
Set Top Box with BCM7268

### Tell us about your OS (Type & version):
Linux firmware

### Have you tried the same use case with AVS Device SDK SampleApp?
Still impossible to logout from Ubuntu vanilla SmartScreen SampleApp

SmartScreen SampleApp is reset and restarted on logout and is leaking. We observe the RSS (using top) and the number of threads increasing (using gdb)
I measure a leak of ~2Mb on each logout/login

I put in attachment :
- 1stlogin_threads.txt: all threads existing in our SampleApp implementation after first login
- 5logins_crash.txt : all threads existing in our SampleApp implementation after five logins (crash occured)

First analysis on my side is that at least some threads are not terminated when sampleapp is reset on restart
- serverThread from Guiclient
- WorkerLoop threads from MediaPlayer(s)

I would like to know if that issue is known on your side and the best way to fix it because I am not sure how to do it properly
Maybe also there is a way to logout without restarting the sampleapp ?

[5logins_crash.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6671369/5logins_crash.txt)
[1stlogin_threads.txt](https://github.com/alexa/alexa-smart-screen-sdk/files/6671370/1stlogin_threads.txt)

**Comment by rom-vdb** [comment]
Patching the vanilla version on ubuntu to call resetDevice() on a navigationEvent, I am able to reproduce the issue

**Comment by sngoc-amazon** [comment]
Hi @rom-vdb,

It appears the issue is the [resetDevice](https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/InteractionManager.cpp#L541) function only resets authorization data on the device. It does not kill the ongoing threads in the execution thread queue. You can test the same using [reset device](https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/InteractionManager.cpp#L541) on Alexa Device SDK using "_k_" key followed by "_enter_" key while app is running.

Please file an issue to [avs-device-sdk](https://github.com/alexa/avs-device-sdk/blob/master/SampleApp/src/InteractionManager.cpp) for additional support on the requirement.

**Comment by rom-vdb** [comment]
Hello @sngoc-amazon 
sorry, but I am not sure to understand that answer.
Since the leaking threads are created by smart screen sdk code, any chance to have a fix ?
I know that there are console commands available with "avs only" sample app, but my problem concern smart screen sdk crash with logout and new login

**Comment by rom-vdb** [comment]
Hello,
in smart screen 2.8.0, is -DAUTH_MANAGER=ON a solution to avoid relaunching a sampleapp instance on logout ? 
If so, It could be a solution to solve leaks on logout/login (when calling resetdevice)
Could you detail that new config option ?
