### ISSUE TITLE
build error for android version with option ‘’ANDROID_LOGGER‘’

### ISSUE THREAD

**Issue by xlb767923274** [alexa/alexa-smart-screen-sdk#99]
**IMPORTANT**: Before you create an issue, please take a look at our [Issue Reporting Guide](https://github.com/alexa/avs-device-sdk/wiki/Issue-Reporting-Guide).

## Briefly summarize your issue:

alexa-smart-screen-sdk\modules\Alexa\SampleApp\src\SampleApplicationComponent.cpp

```
SampleApplicationOptionsComponent getSampleApplicationOptionsComponent() {
    return ComponentAccumulator<>()
        .addComponent(acsdkShared::getComponent())
#ifdef ANDROID_LOGGER
        .addPrimaryFactory(applicationUtilities::androidUtilities::AndroidLogger::getAndroidLogger)
#else
        .addPrimaryFactory(avsCommon::utils::logger::getConsoleLogger)
#endif
#ifdef METRICS_EXTENSION
        .addRetainedFactory(alexaSmartScreenSDK::metrics::MetricsExtension::createMetricRecorderInterface)
#else
        .addRetainedFactory(acsdkDefaultSampleApplicationOptions::NullMetricRecorder::createMetricRecorderInterface)
#endif
        ;
}
```

but the function  getAndroidLogger() havn't been implemented in applicationUtilities::androidUtilities::AndroidLogger

## What is the expected behavior?

build ok

## What behavior are you observing?

build error

## Provide the steps to reproduce the issue, if applicable:

cmake ${MMSDK_SPATH} -DCMAKE_INSTALL_PREFIX=${AVS_IPATH}/install \
        "${CMAKE_PLATFORM_SPECIFIC[@]}" \
        -DCMAKE_BUILD_TYPE=DEBUG \
        -DENABLE_WEBSOCKET_SERVER=ON -DDISABLE_WEBSOCKET_SSL=ON \
        -DWEBSOCKETPP_INCLUDE_DIR=${THIRD_PARTY_PATH}/websocketpp-0.8.1 \
        -DAPL_CORE=ON \
        -DAPLCORE_INCLUDE_DIR=${APL_PATH}/aplcore/include \
		-DAPLCORE_BUILD_INCLUDE_DIR=${APL_PATH}/build/aplcore/include \
        -DAPLCORE_LIB_DIR=${APL_PATH}/build/aplcore \
		-DAPLCORE_RAPIDJSON_INCLUDE_DIR=${APL_PATH}/build/rapidjson-prefix/src/rapidjson/include \
        -DYOGA_INCLUDE_DIR=${APL_PATH}/build/yoga-prefix/src/yoga \
        -DYOGA_LIB_DIR=${APL_PATH}/build/lib \
        -DFFMPEG_LIB_PATH=${AVS_IPATH}/install/lib \
        -DFFMPEG_INCLUDE_DIR=${AVS_IPATH}/install/include/ \
        -DASIO_INCLUDE_DIR=${THIRD_PARTY_PATH} \
        -DANDROID=ON \
        -DANDROID_MEDIA_PLAYER=ON \
        -DANDROID_MICROPHONE=ON \
        -DACSDK_DEBUG_LOG_ENABLED=ON \
        -DANDROID_LOGGER=ON \
        -DRAPIDJSON_HAS_STDSTRING=ON \
        -DANDROID_INC=${THIRD_PARTY_PATH}/android_inc \
        -DARM_ARCH=${TARGET_SYSTEM} 

### What version of the AVS Device SDK are you using?
      <x.y.z>
avs sdk1.24.0   + ss sdk 2.7.0

### Tell us what hardware you're using:
- [ ] Desktop / Laptop
- [ ] Raspberry Pi
- [* ] Other - tell us more: RK3326

### Tell us about your OS (Type & version):
- [ ] Linux
- [ ] MacOS 
- [ ] Raspbian Stretch
- [ ] Raspbian Jessy
- [* ] Other - tell us more: android8.1

### Have you tried the same use case with AVS Device SDK SampleApp?
- [ ] The issue is not applicable to the AVS Device SDK SampleApp.
- [ ] The issue is not reproducible on the AVS Device SDK SampleApp.

**Comment by zsubas** [comment]
Please file this issue to Avs Device SDK team: https://github.com/alexa/avs-device-sdk/issues

They are maintaning the AndroidUtilites, they can steer you to the right direction.

**Comment by xlb767923274** [comment]
> Please file this issue to Avs Device SDK team: https://github.com/alexa/avs-device-sdk/issues
> 
> They are maintaning the AndroidUtilites, they can steer you to the right direction.

The question is why mmsdk uses a function that avs‘s AndroidUtilites does not implement

**Comment by zsubas** [comment]
mmsdk is built on top of avs-sdk, so we are usually following their implementation for common use cases. And this one is one of them. Once this is updated on AVS SDK, it'll be updated on mmsdk as well.

**Comment by xlb767923274** [comment]
> mmsdk is built on top of avs-sdk, so we are usually following their implementation for common use cases. And this one is one of them. Once this is updated on AVS SDK, it'll be updated on mmsdk as well.

Okay, if you internally raise issues for the avs team, would it be more efficient?

**Comment by zsubas** [comment]
I created an internal ticket for this. Since this issue is not related to SSSDK, I'm closing this ticket for now. Feel free to re-open if you have any questions on this topic.
